2018-01-20 21:31:53 [ERROR] - Log -Log.java(41)  -setup
2018-01-20 21:31:53 [ INFO] - Log -Log.java(30)  -DBTool run :delete from book where id >909  param=[]
2018-01-20 22:16:56 [ERROR]-main - Log -Log.java(41)  -setup
2018-01-20 22:16:57 [ INFO]-main - Log -Log.java(30)  -DBTool run :delete from book where id >909  param=[]
2018-01-26 11:54:05 [ERROR]-main - Log -Log.java(41)  -setup
2018-01-26 11:54:06 [ INFO]-main - Log -Log.java(30)  -m = null
2018-01-26 11:54:06 [ INFO]-main - Log -Log.java(30)  -DBTool run :delete from book where id >909  param=[]
2018-01-26 11:54:06 [ERROR]-main - Log -Log.java(41)  -setup
2018-01-26 11:54:06 [ INFO]-main - Log -Log.java(30)  -DBTool run :delete from book where id >909  param=[]
2018-01-26 11:54:06 [ERROR]-main - Log -Log.java(41)  -setup
2018-01-26 11:54:06 [ERROR]-main - Log -Log.java(41)  -testOrder
2018-01-26 11:54:06 [ INFO]-main - Log -Log.java(30)  -Model[id=909,author=null,chaodai=null,name=ss,about=null,type=null,file_name=null,tm_year=null,catalog_id=1]
2018-01-26 11:54:06 [ INFO]-main - Log -Log.java(30)  -DBTool run :delete from book where id >909  param=[]
2018-01-26 11:54:06 [ERROR]-main - Log -Log.java(41)  -setup
2018-01-26 11:54:06 [ERROR]-main - Log -Log.java(41)  -test update
2018-01-26 11:54:06 [ INFO]-main - Log -Log.java(30)  -DBTool run :update book set author=? where id = ?  param=[haha,1]
2018-01-26 11:54:06 [ INFO]-main - Log -Log.java(30)  -1
2018-01-26 11:54:06 [ INFO]-main - Log -Log.java(30)  -DBTool run :delete from book where id >909  param=[]
2018-01-26 11:54:06 [ERROR]-main - Log -Log.java(41)  -setup
2018-01-26 11:54:06 [ERROR]-main - Log -Log.java(41)  -testDel
2018-01-26 11:54:06 [ INFO]-main - Log -Log.java(30)  -m is delete ?no exist
2018-01-26 11:54:06 [ INFO]-main - Log -Log.java(30)  -DBTool run :delete from book where id >909  param=[]
2018-01-26 11:54:06 [ERROR]-main - Log -Log.java(41)  -setup
2018-01-26 11:54:06 [ERROR]-main - Log -Log.java(41)  -testInsert
2018-01-26 11:54:06 [ INFO]-main - Log -Log.java(30)  -insert return 1
2018-01-26 11:54:06 [ INFO]-main - Log -Log.java(30)  -DBTool run :delete from book where id >909  param=[]
2018-01-26 11:54:06 [ERROR]-main - Log -Log.java(41)  -setup
2018-01-26 11:54:06 [ERROR]-main - Log -Log.java(41)  -testInsert
2018-01-26 11:54:06 [ INFO]-main - Log -Log.java(30)  -Model[id=909,author=null,chaodai=null,name=ss,about=null,type=null,file_name=null,tm_year=null,catalog_id=1]
2018-01-26 11:54:06 [ INFO]-main - Log -Log.java(30)  -DBTool run :delete from book where id >909  param=[]
2018-01-26 11:54:06 [ERROR]-main - Log -Log.java(41)  -setup
2018-01-26 11:54:06 [ERROR]-main - Log -Log.java(41)  -testExtra
2018-01-26 11:54:06 [ INFO]-main - Log -Log.java(30)  -Model[id=1,author=haha,chaodai=清  ,name=神农本草经,about= ,type=txt,file_name=000-神农本草经.txt,tm_year=公元1644-1911年  ,catalog_id=1,extra={"haha":"sfsf"}]
2018-01-26 11:54:06 [ INFO]-main - Log -Log.java(30)  -haha = sfsf
2018-01-26 11:54:06 [ INFO]-main - Log -Log.java(30)  -DBTool run :delete from book where id >909  param=[]
2018-01-26 11:54:06 [ERROR]-main - Log -Log.java(41)  -setup
2018-01-26 11:54:06 [ERROR]-main - Log -Log.java(41)  -testGet
2018-01-26 11:54:06 [ INFO]-main - Log -Log.java(30)  -Model[id=1,author=haha,chaodai=清  ,name=神农本草经,about= ,type=txt,file_name=000-神农本草经.txt,tm_year=公元1644-1911年  ,catalog_id=1]
2018-01-26 11:54:06 [ INFO]-main - Log -Log.java(30)  -DBTool run :delete from book where id >909  param=[]
2018-01-26 11:54:06 [ERROR]-main - Log -Log.java(41)  -setup
2018-01-26 11:54:06 [ERROR]-main - Log -Log.java(41)  -testAll
2018-01-26 11:54:06 [ INFO]-main - Log -Log.java(30)  -result1 887
2018-01-26 11:54:06 [ INFO]-main - Log -Log.java(30)  -Model[id=2,author=吴普  ,chaodai=魏晋  ,name=haha,about= ,type=txt,file_name=001-吴普本草.txt,tm_year=公元420年—589  ,catalog_id=1]
2018-01-26 11:54:06 [ INFO]-main - Log -Log.java(30)  -DBTool run :delete from book where id >909  param=[]
2018-01-26 11:54:06 [ERROR]-main - Log -Log.java(41)  -setup
2018-01-26 11:54:06 [ERROR]-main - Log -Log.java(41)  -testCustom
2018-01-26 11:54:06 [ INFO]-main - Log -Log.java(30)  -result2 30
2018-01-26 11:54:06 [ INFO]-main - Log -Log.java(30)  -Model[id=32,author=张秉成  ,chaodai=清  ,name=本草便读,about= ,file_name=031-本草便读.txt,type=txt,tm_year=公元1644-1911年  ,catalog_id=1]
2018-01-26 11:54:06 [ INFO]-main - Log -Log.java(30)  -DBTool run :delete from book where id >909  param=[]
2018-01-26 11:54:06 [ERROR]-main - Log -Log.java(41)  -setup
2018-01-26 11:54:06 [ERROR]-main - Log -Log.java(41)  -testCustomLimit
2018-01-26 11:54:06 [ INFO]-main - Log -Log.java(30)  -DBTool run :delete from book where id >909  param=[]
2018-01-26 11:54:06 [ERROR]-main - Log -Log.java(41)  -setup
2018-01-26 11:54:06 [ERROR]-main - Log -Log.java(41)  -testCustomLimit2
2018-01-26 11:54:06 [ INFO]-main - Log -Log.java(30)  -DBTool run :delete from book where id >909  param=[]
2018-01-26 11:54:06 [ERROR]-main - Log -Log.java(41)  -setup
2018-01-26 11:54:06 [ERROR]-main - Log -Log.java(41)  -testCustomAdd
2018-01-26 11:54:06 [ INFO]-main - Log -Log.java(30)  -result5 30
2018-01-26 11:54:06 [ INFO]-main - Log -Log.java(30)  -Model[id=33,author=陈其瑞  ,chaodai=清  ,name=本草撮要,about= ,file_name=032-本草撮要.txt,type=txt,tm_year=公元1644-1911年  ,catalog_id=1]
2018-01-26 11:54:06 [ INFO]-main - Log -Log.java(30)  -DBTool run :delete from book where id >909  param=[]
2018-01-26 11:54:06 [ERROR]-main - Log -Log.java(41)  -setup
2018-01-26 11:54:06 [ERROR]-main - Log -Log.java(41)  -testEq
2018-01-26 11:54:06 [ INFO]-main - Log -Log.java(30)  -[Model[id=12,author=刘文泰,chaodai=明,name=本草品汇精要,about=,type=txt,file_name=,tm_year=1503,catalog_id=1]]
2018-01-26 11:54:06 [ INFO]-main - Log -Log.java(30)  -[]
2018-01-26 11:54:06 [ INFO]-main - Log -Log.java(30)  -[]
2018-01-26 11:54:06 [ INFO]-main - Log -Log.java(30)  -DBTool run :delete from book where id >909  param=[]
2018-01-26 11:54:06 [ERROR]-main - Log -Log.java(41)  -setup
2018-01-26 11:54:06 [ERROR]-main - Log -Log.java(41)  -testByExample
2018-01-26 11:54:06 [ INFO]-main - Log -Log.java(30)  -1
2018-01-26 11:54:06 [ INFO]-main - Log -Log.java(30)  -[Model[id=12,author=刘文泰,chaodai=明,name=本草品汇精要,about=,type=txt,file_name=,tm_year=1503,catalog_id=1]]
2018-01-26 11:54:06 [ INFO]-main - Log -Log.java(30)  -DBTool run :delete from book where id >909  param=[]
2018-01-26 11:54:06 [ERROR]-main - Log -Log.java(41)  -setup
2018-01-26 11:54:06 [ERROR]-main - Log -Log.java(41)  -testCustomSQL
2018-01-26 11:54:06 [ INFO]-main - Log -Log.java(30)  -result5 30
2018-01-26 11:54:06 [ INFO]-main - Log -Log.java(30)  -Model[author=陈其瑞  ,name=本草撮要]
2018-01-26 11:54:06 [ INFO]-main - Log -Log.java(30)  -DBTool run :delete from book where id >909  param=[]
2018-01-26 11:54:06 [ERROR]-main - Log -Log.java(41)  -setup
2018-01-26 11:54:06 [ INFO]-main - Log -Log.java(30)  -DBTool run :delete from book where id >909  param=[]
2018-01-26 11:55:43 [ERROR]-main - Log -Log.java(41)  -setup
2018-01-26 11:55:43 [ INFO]-main - Log -Log.java(30)  -m = null
2018-01-26 11:55:43 [ INFO]-main - Log -Log.java(30)  -DBTool run :delete from book where id >909  param=[]
2018-01-26 11:55:43 [ERROR]-main - Log -Log.java(41)  -setup
2018-01-26 11:55:43 [ INFO]-main - Log -Log.java(30)  -DBTool run :delete from book where id >909  param=[]
2018-01-26 11:55:43 [ERROR]-main - Log -Log.java(41)  -setup
2018-01-26 11:55:43 [ERROR]-main - Log -Log.java(41)  -testOrder
2018-01-26 11:55:43 [ INFO]-main - Log -Log.java(30)  -Model[id=909,author=null,chaodai=null,name=ss,about=null,type=null,file_name=null,tm_year=null,catalog_id=1]
2018-01-26 11:55:43 [ INFO]-main - Log -Log.java(30)  -DBTool run :delete from book where id >909  param=[]
2018-01-26 11:55:43 [ERROR]-main - Log -Log.java(41)  -setup
2018-01-26 11:55:43 [ERROR]-main - Log -Log.java(41)  -test update
2018-01-26 11:55:43 [ INFO]-main - Log -Log.java(30)  -DBTool run :update book set author=? where id = ?  param=[haha,1]
2018-01-26 11:55:43 [ INFO]-main - Log -Log.java(30)  -1
2018-01-26 11:55:43 [ INFO]-main - Log -Log.java(30)  -DBTool run :delete from book where id >909  param=[]
2018-01-26 11:55:43 [ERROR]-main - Log -Log.java(41)  -setup
2018-01-26 11:55:43 [ERROR]-main - Log -Log.java(41)  -testDel
2018-01-26 11:55:44 [ INFO]-main - Log -Log.java(30)  -m is delete ?no exist
2018-01-26 11:55:44 [ INFO]-main - Log -Log.java(30)  -DBTool run :delete from book where id >909  param=[]
2018-01-26 11:55:44 [ERROR]-main - Log -Log.java(41)  -setup
2018-01-26 11:55:44 [ERROR]-main - Log -Log.java(41)  -testInsert
2018-01-26 11:55:44 [ INFO]-main - Log -Log.java(30)  -insert return 1
2018-01-26 11:55:44 [ INFO]-main - Log -Log.java(30)  -DBTool run :delete from book where id >909  param=[]
2018-01-26 11:55:44 [ERROR]-main - Log -Log.java(41)  -setup
2018-01-26 11:55:44 [ERROR]-main - Log -Log.java(41)  -testInsert
2018-01-26 11:55:44 [ INFO]-main - Log -Log.java(30)  -Model[id=909,author=null,chaodai=null,name=ss,about=null,type=null,file_name=null,tm_year=null,catalog_id=1]
2018-01-26 11:55:44 [ INFO]-main - Log -Log.java(30)  -DBTool run :delete from book where id >909  param=[]
2018-01-26 11:55:44 [ERROR]-main - Log -Log.java(41)  -setup
2018-01-26 11:55:44 [ERROR]-main - Log -Log.java(41)  -testExtra
2018-01-26 11:55:44 [ INFO]-main - Log -Log.java(30)  -Model[id=1,author=haha,chaodai=清  ,name=神农本草经,about= ,type=txt,file_name=000-神农本草经.txt,tm_year=公元1644-1911年  ,catalog_id=1,extra={"haha":"sfsf"}]
2018-01-26 11:55:44 [ INFO]-main - Log -Log.java(30)  -haha = sfsf
2018-01-26 11:55:44 [ INFO]-main - Log -Log.java(30)  -DBTool run :delete from book where id >909  param=[]
2018-01-26 11:55:44 [ERROR]-main - Log -Log.java(41)  -setup
2018-01-26 11:55:44 [ERROR]-main - Log -Log.java(41)  -testGet
2018-01-26 11:55:44 [ INFO]-main - Log -Log.java(30)  -Model[id=1,author=haha,chaodai=清  ,name=神农本草经,about= ,type=txt,file_name=000-神农本草经.txt,tm_year=公元1644-1911年  ,catalog_id=1]
2018-01-26 11:55:44 [ INFO]-main - Log -Log.java(30)  -DBTool run :delete from book where id >909  param=[]
2018-01-26 11:55:44 [ERROR]-main - Log -Log.java(41)  -setup
2018-01-26 11:55:44 [ERROR]-main - Log -Log.java(41)  -testAll
2018-01-26 11:55:44 [ INFO]-main - Log -Log.java(30)  -result1 887
2018-01-26 11:55:44 [ INFO]-main - Log -Log.java(30)  -Model[id=2,author=吴普  ,chaodai=魏晋  ,name=haha,about= ,type=txt,file_name=001-吴普本草.txt,tm_year=公元420年—589  ,catalog_id=1]
2018-01-26 11:55:44 [ INFO]-main - Log -Log.java(30)  -DBTool run :delete from book where id >909  param=[]
2018-01-26 11:55:44 [ERROR]-main - Log -Log.java(41)  -setup
2018-01-26 11:55:44 [ERROR]-main - Log -Log.java(41)  -testCustom
2018-01-26 11:55:55 [ INFO]-main - Log -Log.java(30)  -result2 30
2018-01-26 11:55:55 [ INFO]-main - Log -Log.java(30)  -Model[id=32,author=张秉成  ,chaodai=清  ,name=本草便读,about= ,file_name=031-本草便读.txt,type=txt,tm_year=公元1644-1911年  ,catalog_id=1]
2018-01-26 11:55:55 [ INFO]-main - Log -Log.java(30)  -DBTool run :delete from book where id >909  param=[]
2018-01-26 11:55:55 [ERROR]-main - Log -Log.java(41)  -setup
2018-01-26 11:55:55 [ERROR]-main - Log -Log.java(41)  -testCustomLimit
2018-01-26 12:08:39 [ERROR]-main - Log -Log.java(41)  -setup
2018-01-26 12:08:39 [ INFO]-main - Log -Log.java(30)  -m = null
2018-01-26 12:08:39 [ INFO]-main - Log -Log.java(30)  -DBTool run :delete from book where id >909  param=[]
2018-01-26 12:08:39 [ERROR]-main - Log -Log.java(41)  -setup
2018-01-26 12:08:39 [ INFO]-main - Log -Log.java(30)  -DBTool run :delete from book where id >909  param=[]
2018-01-26 12:08:39 [ERROR]-main - Log -Log.java(41)  -setup
2018-01-26 12:08:39 [ERROR]-main - Log -Log.java(41)  -testOrder
2018-01-26 12:08:39 [ INFO]-main - Log -Log.java(30)  -Model[id=909,author=null,chaodai=null,name=ss,about=null,type=null,file_name=null,tm_year=null,catalog_id=1]
2018-01-26 12:08:39 [ INFO]-main - Log -Log.java(30)  -DBTool run :delete from book where id >909  param=[]
2018-01-26 12:08:39 [ERROR]-main - Log -Log.java(41)  -setup
2018-01-26 12:08:39 [ERROR]-main - Log -Log.java(41)  -test update
2018-01-26 12:08:39 [ INFO]-main - Log -Log.java(30)  -DBTool run :update book set author=? where id = ?  param=[haha,1]
2018-01-26 12:08:39 [ INFO]-main - Log -Log.java(30)  -1
2018-01-26 12:08:39 [ INFO]-main - Log -Log.java(30)  -DBTool run :delete from book where id >909  param=[]
2018-01-26 12:08:39 [ERROR]-main - Log -Log.java(41)  -setup
2018-01-26 12:08:39 [ERROR]-main - Log -Log.java(41)  -testDel
2018-01-26 12:08:40 [ INFO]-main - Log -Log.java(30)  -m is delete ?no exist
2018-01-26 12:08:40 [ INFO]-main - Log -Log.java(30)  -DBTool run :delete from book where id >909  param=[]
2018-01-26 12:08:40 [ERROR]-main - Log -Log.java(41)  -setup
2018-01-26 12:08:40 [ERROR]-main - Log -Log.java(41)  -testInsert
2018-01-26 12:08:40 [ INFO]-main - Log -Log.java(30)  -insert return 1
2018-01-26 12:08:40 [ INFO]-main - Log -Log.java(30)  -DBTool run :delete from book where id >909  param=[]
2018-01-26 12:08:40 [ERROR]-main - Log -Log.java(41)  -setup
2018-01-26 12:08:40 [ERROR]-main - Log -Log.java(41)  -testInsert
2018-01-26 12:08:40 [ INFO]-main - Log -Log.java(30)  -Model[id=909,author=null,chaodai=null,name=ss,about=null,type=null,file_name=null,tm_year=null,catalog_id=1]
2018-01-26 12:08:40 [ INFO]-main - Log -Log.java(30)  -DBTool run :delete from book where id >909  param=[]
2018-01-26 12:08:40 [ERROR]-main - Log -Log.java(41)  -setup
2018-01-26 12:08:40 [ERROR]-main - Log -Log.java(41)  -testExtra
2018-01-26 12:08:40 [ INFO]-main - Log -Log.java(30)  -Model[id=1,author=haha,chaodai=清  ,name=神农本草经,about= ,type=txt,file_name=000-神农本草经.txt,tm_year=公元1644-1911年  ,catalog_id=1,extra={"haha":"sfsf"}]
2018-01-26 12:08:40 [ INFO]-main - Log -Log.java(30)  -haha = sfsf
2018-01-26 12:08:40 [ INFO]-main - Log -Log.java(30)  -DBTool run :delete from book where id >909  param=[]
2018-01-26 12:08:40 [ERROR]-main - Log -Log.java(41)  -setup
2018-01-26 12:08:40 [ERROR]-main - Log -Log.java(41)  -testGet
2018-01-26 12:08:40 [ INFO]-main - Log -Log.java(30)  -Model[id=1,author=haha,chaodai=清  ,name=神农本草经,about= ,type=txt,file_name=000-神农本草经.txt,tm_year=公元1644-1911年  ,catalog_id=1]
2018-01-26 12:08:40 [ INFO]-main - Log -Log.java(30)  -DBTool run :delete from book where id >909  param=[]
2018-01-26 12:08:40 [ERROR]-main - Log -Log.java(41)  -setup
2018-01-26 12:08:40 [ERROR]-main - Log -Log.java(41)  -testAll
2018-01-26 12:08:40 [ INFO]-main - Log -Log.java(30)  -result1 887
2018-01-26 12:08:40 [ INFO]-main - Log -Log.java(30)  -Model[id=2,author=吴普  ,chaodai=魏晋  ,name=haha,about= ,type=txt,file_name=001-吴普本草.txt,tm_year=公元420年—589  ,catalog_id=1]
2018-01-26 12:08:40 [ INFO]-main - Log -Log.java(30)  -DBTool run :delete from book where id >909  param=[]
2018-01-26 12:08:40 [ERROR]-main - Log -Log.java(41)  -setup
2018-01-26 12:08:40 [ERROR]-main - Log -Log.java(41)  -testCustom
2018-01-26 12:08:40 [ INFO]-main - Log -Log.java(30)  -result2 30
2018-01-26 12:08:40 [ INFO]-main - Log -Log.java(30)  -Model[id=32,author=张秉成  ,chaodai=清  ,name=本草便读,about= ,file_name=031-本草便读.txt,type=txt,tm_year=公元1644-1911年  ,catalog_id=1]
2018-01-26 12:08:40 [ INFO]-main - Log -Log.java(30)  -DBTool run :delete from book where id >909  param=[]
2018-01-26 12:08:40 [ERROR]-main - Log -Log.java(41)  -setup
2018-01-26 12:08:40 [ERROR]-main - Log -Log.java(41)  -testCustomAdd
2018-01-26 12:08:40 [ INFO]-main - Log -Log.java(30)  -result5 30
2018-01-26 12:08:40 [ INFO]-main - Log -Log.java(30)  -Model[id=33,author=陈其瑞  ,chaodai=清  ,name=本草撮要,about= ,file_name=032-本草撮要.txt,type=txt,tm_year=公元1644-1911年  ,catalog_id=1]
2018-01-26 12:08:40 [ INFO]-main - Log -Log.java(30)  -DBTool run :delete from book where id >909  param=[]
2018-01-26 12:08:40 [ERROR]-main - Log -Log.java(41)  -setup
2018-01-26 12:08:40 [ERROR]-main - Log -Log.java(41)  -testEq
2018-01-26 12:08:40 [ INFO]-main - Log -Log.java(30)  -[Model[id=12,author=刘文泰,chaodai=明,name=本草品汇精要,about=,type=txt,file_name=,tm_year=1503,catalog_id=1]]
2018-01-26 12:08:40 [ INFO]-main - Log -Log.java(30)  -[]
2018-01-26 12:08:40 [ INFO]-main - Log -Log.java(30)  -[]
2018-01-26 12:08:40 [ INFO]-main - Log -Log.java(30)  -DBTool run :delete from book where id >909  param=[]
2018-01-26 12:08:40 [ERROR]-main - Log -Log.java(41)  -setup
2018-01-26 12:08:40 [ERROR]-main - Log -Log.java(41)  -testByExample
2018-01-26 12:08:40 [ INFO]-main - Log -Log.java(30)  -1
2018-01-26 12:08:40 [ INFO]-main - Log -Log.java(30)  -[Model[id=12,author=刘文泰,chaodai=明,name=本草品汇精要,about=,type=txt,file_name=,tm_year=1503,catalog_id=1]]
2018-01-26 12:08:40 [ INFO]-main - Log -Log.java(30)  -DBTool run :delete from book where id >909  param=[]
2018-01-26 12:08:40 [ERROR]-main - Log -Log.java(41)  -setup
2018-01-26 12:08:40 [ERROR]-main - Log -Log.java(41)  -testCustomSQL
2018-01-26 12:08:40 [ INFO]-main - Log -Log.java(30)  -result5 30
2018-01-26 12:08:40 [ INFO]-main - Log -Log.java(30)  -Model[author=陈其瑞  ,name=本草撮要]
2018-01-26 12:08:40 [ INFO]-main - Log -Log.java(30)  -DBTool run :delete from book where id >909  param=[]
2018-01-26 12:08:40 [ERROR]-main - Log -Log.java(41)  -setup
2018-01-26 12:08:40 [ INFO]-main - Log -Log.java(30)  -DBTool run :delete from book where id >909  param=[]
2018-01-26 12:09:21 [ INFO]-main - Log -Log.java(30)  -DBTool run :delete from book where id >909  param=[]
2018-01-26 12:11:08 [ERROR]-main - Log -Log.java(41)  -setup
2018-01-26 12:11:09 [ INFO]-main - Log -Log.java(30)  -DBTool run :delete from book where id >909  param=[]
2018-01-26 12:11:53 [ INFO]-main - Log -Log.java(30)  -5
2018-01-26 12:11:59 [ INFO]-main - Log -Log.java(30)  -5
2018-01-26 12:14:14 [ INFO]-main - Log -Log.java(30)  -5
2018-01-26 12:14:19 [ INFO]-main - Log -Log.java(30)  -5
2018-01-26 12:15:19 [ INFO]-main - Log -Log.java(30)  -5
2018-01-26 12:15:24 [ INFO]-main - Log -Log.java(30)  -5
2018-01-27 10:26:35 [ERROR]-main - Log -Log.java(41)  -setup
2018-01-27 10:26:35 [ INFO]-main - Log -Log.java(30)  -m = null
2018-01-27 10:26:35 [ INFO]-main - Log -Log.java(30)  -DBTool run :delete from book where id >909  param=[]
2018-01-27 10:26:35 [ERROR]-main - Log -Log.java(41)  -setup
2018-01-27 10:26:35 [ INFO]-main - Log -Log.java(30)  -DBTool run :delete from book where id >909  param=[]
2018-01-27 10:26:35 [ERROR]-main - Log -Log.java(41)  -setup
2018-01-27 10:26:35 [ERROR]-main - Log -Log.java(41)  -testOrder
2018-01-27 10:26:35 [ INFO]-main - Log -Log.java(30)  -Model[id=909,author=null,chaodai=null,name=ss,about=null,type=null,file_name=null,tm_year=null,catalog_id=1]
2018-01-27 10:26:35 [ INFO]-main - Log -Log.java(30)  -DBTool run :delete from book where id >909  param=[]
2018-01-27 10:26:35 [ERROR]-main - Log -Log.java(41)  -setup
2018-01-27 10:26:35 [ERROR]-main - Log -Log.java(41)  -test update
2018-01-27 10:26:35 [ INFO]-main - Log -Log.java(30)  -DBTool run :update book set author=? where id = ?  param=[haha,1]
2018-01-27 10:26:35 [ INFO]-main - Log -Log.java(30)  -1
2018-01-27 10:26:35 [ INFO]-main - Log -Log.java(30)  -DBTool run :delete from book where id >909  param=[]
2018-01-27 10:26:35 [ERROR]-main - Log -Log.java(41)  -setup
2018-01-27 10:26:35 [ERROR]-main - Log -Log.java(41)  -testDel
2018-01-27 10:26:36 [ INFO]-main - Log -Log.java(30)  -m is delete ?no exist
2018-01-27 10:26:36 [ INFO]-main - Log -Log.java(30)  -DBTool run :delete from book where id >909  param=[]
2018-01-27 10:26:36 [ERROR]-main - Log -Log.java(41)  -setup
2018-01-27 10:26:36 [ERROR]-main - Log -Log.java(41)  -testInsert
2018-01-27 10:26:36 [ INFO]-main - Log -Log.java(30)  -insert return 1
2018-01-27 10:26:36 [ INFO]-main - Log -Log.java(30)  -DBTool run :delete from book where id >909  param=[]
2018-01-27 10:26:36 [ERROR]-main - Log -Log.java(41)  -setup
2018-01-27 10:26:36 [ERROR]-main - Log -Log.java(41)  -testInsert
2018-01-27 10:26:36 [ INFO]-main - Log -Log.java(30)  -Model[id=909,author=null,chaodai=null,name=ss,about=null,type=null,file_name=null,tm_year=null,catalog_id=1]
2018-01-27 10:26:36 [ INFO]-main - Log -Log.java(30)  -DBTool run :delete from book where id >909  param=[]
2018-01-27 10:26:36 [ERROR]-main - Log -Log.java(41)  -setup
2018-01-27 10:26:36 [ERROR]-main - Log -Log.java(41)  -testExtra
2018-01-27 10:26:36 [ INFO]-main - Log -Log.java(30)  -Model[id=1,author=haha,chaodai=清  ,name=神农本草经,about= ,type=txt,file_name=000-神农本草经.txt,tm_year=公元1644-1911年  ,catalog_id=1,extra={"haha":"sfsf"}]
2018-01-27 10:26:36 [ INFO]-main - Log -Log.java(30)  -haha = sfsf
2018-01-27 10:26:36 [ INFO]-main - Log -Log.java(30)  -DBTool run :delete from book where id >909  param=[]
2018-01-27 10:26:36 [ERROR]-main - Log -Log.java(41)  -setup
2018-01-27 10:26:36 [ERROR]-main - Log -Log.java(41)  -testGet
2018-01-27 10:26:36 [ INFO]-main - Log -Log.java(30)  -Model[id=1,author=haha,chaodai=清  ,name=神农本草经,about= ,type=txt,file_name=000-神农本草经.txt,tm_year=公元1644-1911年  ,catalog_id=1]
2018-01-27 10:26:36 [ INFO]-main - Log -Log.java(30)  -DBTool run :delete from book where id >909  param=[]
2018-01-27 10:26:36 [ERROR]-main - Log -Log.java(41)  -setup
2018-01-27 10:26:36 [ERROR]-main - Log -Log.java(41)  -testAll
2018-01-27 10:26:36 [ INFO]-main - Log -Log.java(30)  -result1 887
2018-01-27 10:26:36 [ INFO]-main - Log -Log.java(30)  -Model[id=2,author=吴普  ,chaodai=魏晋  ,name=haha,about= ,type=txt,file_name=001-吴普本草.txt,tm_year=公元420年—589  ,catalog_id=1]
2018-01-27 10:26:36 [ INFO]-main - Log -Log.java(30)  -DBTool run :delete from book where id >909  param=[]
2018-01-27 10:26:36 [ERROR]-main - Log -Log.java(41)  -setup
2018-01-27 10:26:36 [ERROR]-main - Log -Log.java(41)  -testCustom
2018-01-27 10:26:36 [ INFO]-main - Log -Log.java(30)  -result2 30
2018-01-27 10:26:36 [ INFO]-main - Log -Log.java(30)  -Model[id=32,author=张秉成  ,chaodai=清  ,name=本草便读,about= ,file_name=031-本草便读.txt,type=txt,tm_year=公元1644-1911年  ,catalog_id=1]
2018-01-27 10:26:36 [ INFO]-main - Log -Log.java(30)  -DBTool run :delete from book where id >909  param=[]
2018-01-27 10:26:36 [ERROR]-main - Log -Log.java(41)  -setup
2018-01-27 10:26:36 [ERROR]-main - Log -Log.java(41)  -testEq
2018-01-27 10:26:36 [ INFO]-main - Log -Log.java(30)  -[Model[id=12,author=刘文泰,chaodai=明,name=本草品汇精要,about=,type=txt,file_name=,tm_year=1503,catalog_id=1]]
2018-01-27 10:26:36 [ INFO]-main - Log -Log.java(30)  -[]
2018-01-27 10:26:36 [ INFO]-main - Log -Log.java(30)  -[]
2018-01-27 10:26:36 [ INFO]-main - Log -Log.java(30)  -DBTool run :delete from book where id >909  param=[]
2018-01-27 10:26:36 [ERROR]-main - Log -Log.java(41)  -setup
2018-01-27 10:26:36 [ERROR]-main - Log -Log.java(41)  -testByExample
2018-01-27 10:26:36 [ INFO]-main - Log -Log.java(30)  -1
2018-01-27 10:26:36 [ INFO]-main - Log -Log.java(30)  -[Model[id=12,author=刘文泰,chaodai=明,name=本草品汇精要,about=,type=txt,file_name=,tm_year=1503,catalog_id=1]]
2018-01-27 10:26:36 [ INFO]-main - Log -Log.java(30)  -DBTool run :delete from book where id >909  param=[]
2018-01-27 10:26:36 [ERROR]-main - Log -Log.java(41)  -setup
2018-01-27 10:26:36 [ INFO]-main - Log -Log.java(30)  -DBTool run :delete from book where id >909  param=[]
2018-01-27 10:26:45 [ INFO]-main - Log -Log.java(30)  -DBTool run :delete from book where id >909  param=[]
2018-01-27 10:26:53 [ERROR]-main - Log -Log.java(41)  -setup
2018-01-27 10:26:54 [ INFO]-main - Log -Log.java(30)  -DBTool run :delete from book where id >909  param=[]
2018-02-03 17:23:09 [ERROR]-main - Log -Log.java(41)  -setup
2018-02-03 17:23:10 [ INFO]-main - Log -Log.java(30)  -DBTool run :delete from book where id >909  param=[]
2018-02-03 17:45:33 [ERROR]-main - Log -Log.java(41)  -setup
2018-02-03 17:45:34 [ INFO]-main - Log -Log.java(30)  -DBTool run :delete from book where id >909  param=[]
2018-02-03 17:46:15 [ERROR]-main - Log -Log.java(41)  -setup
2018-02-03 17:46:16 [ INFO]-main - Log -Log.java(30)  -DBTool run :delete from book where id >909  param=[]
2018-02-03 17:46:45 [ERROR]-main - Log -Log.java(41)  -setup
2018-02-03 17:46:45 [ INFO]-main - Log -Log.java(30)  -DBTool run :delete from book where id >909  param=[]
2018-02-12 09:02:17 [ERROR]-main - Log -Log.java(41)  -setup
2018-02-12 09:02:18 [ INFO]-main - Log -Log.java(30)  -m = null
2018-02-12 09:02:18 [ INFO]-main - Log -Log.java(30)  -DBTool run :delete from book where id >909  param=[]
2018-02-12 09:02:18 [ERROR]-main - Log -Log.java(41)  -setup
2018-02-12 09:02:18 [ INFO]-main - Log -Log.java(30)  -DBTool run :delete from book where id >909  param=[]
2018-02-12 09:02:18 [ERROR]-main - Log -Log.java(41)  -setup
2018-02-12 09:02:18 [ERROR]-main - Log -Log.java(41)  -testOrder
2018-02-12 09:02:18 [ INFO]-main - Log -Log.java(30)  -Model[id=909,author=null,chaodai=null,name=ss,about=null,type=null,file_name=null,tm_year=null,catalog_id=1]
2018-02-12 09:02:18 [ INFO]-main - Log -Log.java(30)  -DBTool run :delete from book where id >909  param=[]
2018-02-12 09:02:18 [ERROR]-main - Log -Log.java(41)  -setup
2018-02-12 09:02:18 [ERROR]-main - Log -Log.java(41)  -test update
2018-02-12 09:02:18 [ INFO]-main - Log -Log.java(30)  -DBTool run :update book set author=? where id = ?  param=[haha,1]
2018-02-12 09:02:18 [ INFO]-main - Log -Log.java(30)  -1
2018-02-12 09:02:18 [ INFO]-main - Log -Log.java(30)  -DBTool run :delete from book where id >909  param=[]
2018-02-12 09:02:18 [ERROR]-main - Log -Log.java(41)  -setup
2018-02-12 09:02:18 [ERROR]-main - Log -Log.java(41)  -testDel
2018-02-12 09:02:18 [ INFO]-main - Log -Log.java(30)  -m is delete ?no exist
2018-02-12 09:02:18 [ INFO]-main - Log -Log.java(30)  -DBTool run :delete from book where id >909  param=[]
2018-02-12 09:02:18 [ERROR]-main - Log -Log.java(41)  -setup
2018-02-12 09:02:18 [ERROR]-main - Log -Log.java(41)  -testInsert
2018-02-12 09:02:18 [ INFO]-main - Log -Log.java(30)  -insert return 1
2018-02-12 09:02:18 [ INFO]-main - Log -Log.java(30)  -DBTool run :delete from book where id >909  param=[]
2018-02-12 09:02:18 [ERROR]-main - Log -Log.java(41)  -setup
2018-02-12 09:02:18 [ERROR]-main - Log -Log.java(41)  -testInsert
2018-02-12 09:02:18 [ INFO]-main - Log -Log.java(30)  -Model[id=909,author=null,chaodai=null,name=ss,about=null,type=null,file_name=null,tm_year=null,catalog_id=1]
2018-02-12 09:02:18 [ INFO]-main - Log -Log.java(30)  -DBTool run :delete from book where id >909  param=[]
2018-02-12 09:02:18 [ERROR]-main - Log -Log.java(41)  -setup
2018-02-12 09:02:18 [ERROR]-main - Log -Log.java(41)  -testExtra
2018-02-12 09:02:18 [ INFO]-main - Log -Log.java(30)  -Model[id=1,author=haha,chaodai=清  ,name=神农本草经,about= ,type=txt,file_name=000-神农本草经.txt,tm_year=公元1644-1911年  ,catalog_id=1,extra={"haha":"sfsf"}]
2018-02-12 09:02:18 [ INFO]-main - Log -Log.java(30)  -haha = sfsf
2018-02-12 09:02:18 [ INFO]-main - Log -Log.java(30)  -DBTool run :delete from book where id >909  param=[]
2018-02-12 09:02:18 [ERROR]-main - Log -Log.java(41)  -setup
2018-02-12 09:02:18 [ERROR]-main - Log -Log.java(41)  -testGet
2018-02-12 09:02:18 [ INFO]-main - Log -Log.java(30)  -Model[id=1,author=haha,chaodai=清  ,name=神农本草经,about= ,type=txt,file_name=000-神农本草经.txt,tm_year=公元1644-1911年  ,catalog_id=1]
2018-02-12 09:02:18 [ INFO]-main - Log -Log.java(30)  -DBTool run :delete from book where id >909  param=[]
2018-02-12 09:02:18 [ERROR]-main - Log -Log.java(41)  -setup
2018-02-12 09:02:18 [ERROR]-main - Log -Log.java(41)  -testAll
2018-02-12 09:02:18 [ INFO]-main - Log -Log.java(30)  -result1 887
2018-02-12 09:02:18 [ INFO]-main - Log -Log.java(30)  -Model[id=2,author=吴普  ,chaodai=魏晋  ,name=haha,about= ,type=txt,file_name=001-吴普本草.txt,tm_year=公元420年—589  ,catalog_id=1]
2018-02-12 09:02:18 [ INFO]-main - Log -Log.java(30)  -DBTool run :delete from book where id >909  param=[]
2018-02-12 09:02:18 [ERROR]-main - Log -Log.java(41)  -setup
2018-02-12 09:02:18 [ERROR]-main - Log -Log.java(41)  -testCustom
2018-02-12 09:02:19 [ INFO]-main - Log -Log.java(30)  -result2 30
2018-02-12 09:02:19 [ INFO]-main - Log -Log.java(30)  -Model[id=32,author=张秉成  ,chaodai=清  ,name=本草便读,about= ,file_name=031-本草便读.txt,type=txt,tm_year=公元1644-1911年  ,catalog_id=1]
2018-02-12 09:02:19 [ INFO]-main - Log -Log.java(30)  -DBTool run :delete from book where id >909  param=[]
2018-02-12 09:02:19 [ERROR]-main - Log -Log.java(41)  -setup
2018-02-12 09:02:19 [ERROR]-main - Log -Log.java(41)  -testEq
2018-02-12 09:02:19 [ INFO]-main - Log -Log.java(30)  -[Model[id=12,author=刘文泰,chaodai=明,name=本草品汇精要,about=,type=txt,file_name=,tm_year=1503,catalog_id=1]]
2018-02-12 09:02:19 [ INFO]-main - Log -Log.java(30)  -[]
2018-02-12 09:02:19 [ INFO]-main - Log -Log.java(30)  -[]
2018-02-12 09:02:19 [ INFO]-main - Log -Log.java(30)  -DBTool run :delete from book where id >909  param=[]
2018-02-12 09:02:19 [ERROR]-main - Log -Log.java(41)  -setup
2018-02-12 09:02:19 [ERROR]-main - Log -Log.java(41)  -testByExample
2018-02-12 09:02:19 [ INFO]-main - Log -Log.java(30)  -1
2018-02-12 09:02:19 [ INFO]-main - Log -Log.java(30)  -[Model[id=12,author=刘文泰,chaodai=明,name=本草品汇精要,about=,type=txt,file_name=,tm_year=1503,catalog_id=1]]
2018-02-12 09:02:19 [ INFO]-main - Log -Log.java(30)  -DBTool run :delete from book where id >909  param=[]
2018-02-12 09:02:19 [ERROR]-main - Log -Log.java(41)  -setup
2018-02-12 09:02:19 [ INFO]-main - Log -Log.java(30)  -DBTool run :delete from book where id >909  param=[]
2018-02-12 09:06:24 [ INFO]-main - Log -Log.java(30)  -DBTool run :delete from book where id >909  param=[]
2018-02-12 09:06:54 [ERROR]-main - Log -Log.java(41)  -setup
2018-02-12 09:06:55 [ERROR]-main - Log -Log.java(41)  -exec sql fail insert into `catalog`(`id`,`name`) values(?,?) ,param = 1,本草_haha_haha_haha_haha_haha_haha
2018-02-12 09:06:55 [ERROR]-main - Log -Log.java(41)  -com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Duplicate entry '1' for key 1
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:39)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:27)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:513)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.Util.getInstance(Util.java:408)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:936)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3973)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3909)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2527)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2680)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2484)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1858)
	at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2079)
	at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2013)
	at com.mysql.jdbc.PreparedStatement.executeLargeUpdate(PreparedStatement.java:5104)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1998)
	at org.docshare.orm.DBHelper.updateWithArray(DBHelper.java:171)
	at org.docshare.orm.mysql.MySQLDelegate.save(MySQLDelegate.java:85)
	at org.docshare.orm.DBTool.save(DBTool.java:197)
	at org.docshare.orm.DBTool.save(DBTool.java:180)
	at org.docshare.orm.DBTool.save(DBTool.java:183)
	at org.docshare.test.TestORM3.testObject(TestORM3.java:38)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at junit.framework.TestCase.runTest(TestCase.java:168)
	at junit.framework.TestCase.runBare(TestCase.java:134)
	at junit.framework.TestResult$1.protect(TestResult.java:110)
	at junit.framework.TestResult.runProtected(TestResult.java:128)
	at junit.framework.TestResult.run(TestResult.java:113)
	at junit.framework.TestCase.run(TestCase.java:124)
	at junit.framework.TestSuite.runTest(TestSuite.java:243)
	at junit.framework.TestSuite.run(TestSuite.java:238)
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:83)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)

2018-02-12 09:06:55 [ERROR]-main - Log -Log.java(41)  -exec sql fail insert into `catalog`(`id`,`name`) values(?,?) ,param = 2,方剂_haha_haha_haha_haha_haha_haha
2018-02-12 09:06:55 [ERROR]-main - Log -Log.java(41)  -com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Duplicate entry '2' for key 1
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:39)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:27)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:513)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.Util.getInstance(Util.java:408)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:936)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3973)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3909)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2527)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2680)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2484)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1858)
	at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2079)
	at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2013)
	at com.mysql.jdbc.PreparedStatement.executeLargeUpdate(PreparedStatement.java:5104)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1998)
	at org.docshare.orm.DBHelper.updateWithArray(DBHelper.java:171)
	at org.docshare.orm.mysql.MySQLDelegate.save(MySQLDelegate.java:85)
	at org.docshare.orm.DBTool.save(DBTool.java:197)
	at org.docshare.orm.DBTool.save(DBTool.java:180)
	at org.docshare.orm.DBTool.save(DBTool.java:183)
	at org.docshare.test.TestORM3.testObject(TestORM3.java:38)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at junit.framework.TestCase.runTest(TestCase.java:168)
	at junit.framework.TestCase.runBare(TestCase.java:134)
	at junit.framework.TestResult$1.protect(TestResult.java:110)
	at junit.framework.TestResult.runProtected(TestResult.java:128)
	at junit.framework.TestResult.run(TestResult.java:113)
	at junit.framework.TestCase.run(TestCase.java:124)
	at junit.framework.TestSuite.runTest(TestSuite.java:243)
	at junit.framework.TestSuite.run(TestSuite.java:238)
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:83)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)

2018-02-12 09:06:55 [ERROR]-main - Log -Log.java(41)  -exec sql fail insert into `catalog`(`id`,`name`) values(?,?) ,param = 3,医案_haha_haha_haha_haha_haha_haha
2018-02-12 09:06:55 [ERROR]-main - Log -Log.java(41)  -com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Duplicate entry '3' for key 1
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:39)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:27)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:513)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.Util.getInstance(Util.java:408)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:936)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3973)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3909)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2527)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2680)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2484)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1858)
	at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2079)
	at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2013)
	at com.mysql.jdbc.PreparedStatement.executeLargeUpdate(PreparedStatement.java:5104)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1998)
	at org.docshare.orm.DBHelper.updateWithArray(DBHelper.java:171)
	at org.docshare.orm.mysql.MySQLDelegate.save(MySQLDelegate.java:85)
	at org.docshare.orm.DBTool.save(DBTool.java:197)
	at org.docshare.orm.DBTool.save(DBTool.java:180)
	at org.docshare.orm.DBTool.save(DBTool.java:183)
	at org.docshare.test.TestORM3.testObject(TestORM3.java:38)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at junit.framework.TestCase.runTest(TestCase.java:168)
	at junit.framework.TestCase.runBare(TestCase.java:134)
	at junit.framework.TestResult$1.protect(TestResult.java:110)
	at junit.framework.TestResult.runProtected(TestResult.java:128)
	at junit.framework.TestResult.run(TestResult.java:113)
	at junit.framework.TestCase.run(TestCase.java:124)
	at junit.framework.TestSuite.runTest(TestSuite.java:243)
	at junit.framework.TestSuite.run(TestSuite.java:238)
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:83)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)

2018-02-12 09:06:55 [ERROR]-main - Log -Log.java(41)  -exec sql fail insert into `catalog`(`id`,`name`) values(?,?) ,param = 4,经论_haha_haha_haha_haha_haha_haha
2018-02-12 09:06:55 [ERROR]-main - Log -Log.java(41)  -com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Duplicate entry '4' for key 1
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:39)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:27)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:513)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.Util.getInstance(Util.java:408)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:936)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3973)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3909)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2527)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2680)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2484)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1858)
	at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2079)
	at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2013)
	at com.mysql.jdbc.PreparedStatement.executeLargeUpdate(PreparedStatement.java:5104)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1998)
	at org.docshare.orm.DBHelper.updateWithArray(DBHelper.java:171)
	at org.docshare.orm.mysql.MySQLDelegate.save(MySQLDelegate.java:85)
	at org.docshare.orm.DBTool.save(DBTool.java:197)
	at org.docshare.orm.DBTool.save(DBTool.java:180)
	at org.docshare.orm.DBTool.save(DBTool.java:183)
	at org.docshare.test.TestORM3.testObject(TestORM3.java:38)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at junit.framework.TestCase.runTest(TestCase.java:168)
	at junit.framework.TestCase.runBare(TestCase.java:134)
	at junit.framework.TestResult$1.protect(TestResult.java:110)
	at junit.framework.TestResult.runProtected(TestResult.java:128)
	at junit.framework.TestResult.run(TestResult.java:113)
	at junit.framework.TestCase.run(TestCase.java:124)
	at junit.framework.TestSuite.runTest(TestSuite.java:243)
	at junit.framework.TestSuite.run(TestSuite.java:238)
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:83)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)

2018-02-12 09:06:55 [ERROR]-main - Log -Log.java(41)  -exec sql fail insert into `catalog`(`id`,`name`) values(?,?) ,param = 5,专科_haha_haha_haha_haha_haha_haha
2018-02-12 09:06:55 [ERROR]-main - Log -Log.java(41)  -com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Duplicate entry '5' for key 1
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:39)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:27)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:513)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.Util.getInstance(Util.java:408)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:936)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3973)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3909)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2527)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2680)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2484)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1858)
	at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2079)
	at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2013)
	at com.mysql.jdbc.PreparedStatement.executeLargeUpdate(PreparedStatement.java:5104)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1998)
	at org.docshare.orm.DBHelper.updateWithArray(DBHelper.java:171)
	at org.docshare.orm.mysql.MySQLDelegate.save(MySQLDelegate.java:85)
	at org.docshare.orm.DBTool.save(DBTool.java:197)
	at org.docshare.orm.DBTool.save(DBTool.java:180)
	at org.docshare.orm.DBTool.save(DBTool.java:183)
	at org.docshare.test.TestORM3.testObject(TestORM3.java:38)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at junit.framework.TestCase.runTest(TestCase.java:168)
	at junit.framework.TestCase.runBare(TestCase.java:134)
	at junit.framework.TestResult$1.protect(TestResult.java:110)
	at junit.framework.TestResult.runProtected(TestResult.java:128)
	at junit.framework.TestResult.run(TestResult.java:113)
	at junit.framework.TestCase.run(TestCase.java:124)
	at junit.framework.TestSuite.runTest(TestSuite.java:243)
	at junit.framework.TestSuite.run(TestSuite.java:238)
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:83)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)

2018-02-12 09:06:55 [ERROR]-main - Log -Log.java(41)  -exec sql fail insert into `catalog`(`id`,`name`) values(?,?) ,param = 7,炮制_haha_haha_haha_haha_haha_haha
2018-02-12 09:06:55 [ERROR]-main - Log -Log.java(41)  -com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Duplicate entry '7' for key 1
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:39)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:27)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:513)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.Util.getInstance(Util.java:408)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:936)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3973)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3909)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2527)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2680)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2484)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1858)
	at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2079)
	at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2013)
	at com.mysql.jdbc.PreparedStatement.executeLargeUpdate(PreparedStatement.java:5104)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1998)
	at org.docshare.orm.DBHelper.updateWithArray(DBHelper.java:171)
	at org.docshare.orm.mysql.MySQLDelegate.save(MySQLDelegate.java:85)
	at org.docshare.orm.DBTool.save(DBTool.java:197)
	at org.docshare.orm.DBTool.save(DBTool.java:180)
	at org.docshare.orm.DBTool.save(DBTool.java:183)
	at org.docshare.test.TestORM3.testObject(TestORM3.java:38)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at junit.framework.TestCase.runTest(TestCase.java:168)
	at junit.framework.TestCase.runBare(TestCase.java:134)
	at junit.framework.TestResult$1.protect(TestResult.java:110)
	at junit.framework.TestResult.runProtected(TestResult.java:128)
	at junit.framework.TestResult.run(TestResult.java:113)
	at junit.framework.TestCase.run(TestCase.java:124)
	at junit.framework.TestSuite.runTest(TestSuite.java:243)
	at junit.framework.TestSuite.run(TestSuite.java:238)
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:83)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)

2018-02-12 09:06:55 [ERROR]-main - Log -Log.java(41)  -exec sql fail insert into `catalog`(`id`,`name`) values(?,?) ,param = 8,针灸_haha_haha_haha_haha_haha_haha
2018-02-12 09:06:55 [ERROR]-main - Log -Log.java(41)  -com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Duplicate entry '8' for key 1
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:39)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:27)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:513)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.Util.getInstance(Util.java:408)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:936)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3973)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3909)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2527)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2680)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2484)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1858)
	at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2079)
	at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2013)
	at com.mysql.jdbc.PreparedStatement.executeLargeUpdate(PreparedStatement.java:5104)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1998)
	at org.docshare.orm.DBHelper.updateWithArray(DBHelper.java:171)
	at org.docshare.orm.mysql.MySQLDelegate.save(MySQLDelegate.java:85)
	at org.docshare.orm.DBTool.save(DBTool.java:197)
	at org.docshare.orm.DBTool.save(DBTool.java:180)
	at org.docshare.orm.DBTool.save(DBTool.java:183)
	at org.docshare.test.TestORM3.testObject(TestORM3.java:38)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at junit.framework.TestCase.runTest(TestCase.java:168)
	at junit.framework.TestCase.runBare(TestCase.java:134)
	at junit.framework.TestResult$1.protect(TestResult.java:110)
	at junit.framework.TestResult.runProtected(TestResult.java:128)
	at junit.framework.TestResult.run(TestResult.java:113)
	at junit.framework.TestCase.run(TestCase.java:124)
	at junit.framework.TestSuite.runTest(TestSuite.java:243)
	at junit.framework.TestSuite.run(TestSuite.java:238)
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:83)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)

2018-02-12 09:06:55 [ERROR]-main - Log -Log.java(41)  -exec sql fail insert into `catalog`(`id`,`name`) values(?,?) ,param = 9,五运六气_haha_haha_haha_haha_haha_haha
2018-02-12 09:06:55 [ERROR]-main - Log -Log.java(41)  -com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Duplicate entry '9' for key 1
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:39)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:27)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:513)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.Util.getInstance(Util.java:408)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:936)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3973)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3909)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2527)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2680)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2484)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1858)
	at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2079)
	at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2013)
	at com.mysql.jdbc.PreparedStatement.executeLargeUpdate(PreparedStatement.java:5104)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1998)
	at org.docshare.orm.DBHelper.updateWithArray(DBHelper.java:171)
	at org.docshare.orm.mysql.MySQLDelegate.save(MySQLDelegate.java:85)
	at org.docshare.orm.DBTool.save(DBTool.java:197)
	at org.docshare.orm.DBTool.save(DBTool.java:180)
	at org.docshare.orm.DBTool.save(DBTool.java:183)
	at org.docshare.test.TestORM3.testObject(TestORM3.java:38)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at junit.framework.TestCase.runTest(TestCase.java:168)
	at junit.framework.TestCase.runBare(TestCase.java:134)
	at junit.framework.TestResult$1.protect(TestResult.java:110)
	at junit.framework.TestResult.runProtected(TestResult.java:128)
	at junit.framework.TestResult.run(TestResult.java:113)
	at junit.framework.TestCase.run(TestCase.java:124)
	at junit.framework.TestSuite.runTest(TestSuite.java:243)
	at junit.framework.TestSuite.run(TestSuite.java:238)
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:83)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)

2018-02-12 09:06:55 [ERROR]-main - Log -Log.java(41)  -exec sql fail insert into `catalog`(`id`,`name`) values(?,?) ,param = 10,诊断_haha_haha_haha_haha_haha_haha
2018-02-12 09:06:55 [ERROR]-main - Log -Log.java(41)  -com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Duplicate entry '10' for key 1
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:39)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:27)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:513)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.Util.getInstance(Util.java:408)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:936)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3973)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3909)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2527)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2680)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2484)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1858)
	at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2079)
	at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2013)
	at com.mysql.jdbc.PreparedStatement.executeLargeUpdate(PreparedStatement.java:5104)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1998)
	at org.docshare.orm.DBHelper.updateWithArray(DBHelper.java:171)
	at org.docshare.orm.mysql.MySQLDelegate.save(MySQLDelegate.java:85)
	at org.docshare.orm.DBTool.save(DBTool.java:197)
	at org.docshare.orm.DBTool.save(DBTool.java:180)
	at org.docshare.orm.DBTool.save(DBTool.java:183)
	at org.docshare.test.TestORM3.testObject(TestORM3.java:38)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at junit.framework.TestCase.runTest(TestCase.java:168)
	at junit.framework.TestCase.runBare(TestCase.java:134)
	at junit.framework.TestResult$1.protect(TestResult.java:110)
	at junit.framework.TestResult.runProtected(TestResult.java:128)
	at junit.framework.TestResult.run(TestResult.java:113)
	at junit.framework.TestCase.run(TestCase.java:124)
	at junit.framework.TestSuite.runTest(TestSuite.java:243)
	at junit.framework.TestSuite.run(TestSuite.java:238)
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:83)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)

2018-02-12 09:06:55 [ERROR]-main - Log -Log.java(41)  -exec sql fail insert into `catalog`(`id`,`name`) values(?,?) ,param = 11,养生_haha_haha_haha_haha_haha_haha
2018-02-12 09:06:55 [ERROR]-main - Log -Log.java(41)  -com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Duplicate entry '11' for key 1
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:39)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:27)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:513)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.Util.getInstance(Util.java:408)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:936)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3973)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3909)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2527)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2680)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2484)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1858)
	at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2079)
	at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2013)
	at com.mysql.jdbc.PreparedStatement.executeLargeUpdate(PreparedStatement.java:5104)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1998)
	at org.docshare.orm.DBHelper.updateWithArray(DBHelper.java:171)
	at org.docshare.orm.mysql.MySQLDelegate.save(MySQLDelegate.java:85)
	at org.docshare.orm.DBTool.save(DBTool.java:197)
	at org.docshare.orm.DBTool.save(DBTool.java:180)
	at org.docshare.orm.DBTool.save(DBTool.java:183)
	at org.docshare.test.TestORM3.testObject(TestORM3.java:38)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at junit.framework.TestCase.runTest(TestCase.java:168)
	at junit.framework.TestCase.runBare(TestCase.java:134)
	at junit.framework.TestResult$1.protect(TestResult.java:110)
	at junit.framework.TestResult.runProtected(TestResult.java:128)
	at junit.framework.TestResult.run(TestResult.java:113)
	at junit.framework.TestCase.run(TestCase.java:124)
	at junit.framework.TestSuite.runTest(TestSuite.java:243)
	at junit.framework.TestSuite.run(TestSuite.java:238)
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:83)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)

2018-02-12 09:06:55 [ERROR]-main - Log -Log.java(41)  -exec sql fail insert into `catalog`(`id`,`name`) values(?,?) ,param = 12,周易_haha_haha_haha_haha_haha_haha
2018-02-12 09:06:55 [ERROR]-main - Log -Log.java(41)  -com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Duplicate entry '12' for key 1
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:39)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:27)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:513)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.Util.getInstance(Util.java:408)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:936)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3973)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3909)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2527)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2680)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2484)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1858)
	at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2079)
	at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2013)
	at com.mysql.jdbc.PreparedStatement.executeLargeUpdate(PreparedStatement.java:5104)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1998)
	at org.docshare.orm.DBHelper.updateWithArray(DBHelper.java:171)
	at org.docshare.orm.mysql.MySQLDelegate.save(MySQLDelegate.java:85)
	at org.docshare.orm.DBTool.save(DBTool.java:197)
	at org.docshare.orm.DBTool.save(DBTool.java:180)
	at org.docshare.orm.DBTool.save(DBTool.java:183)
	at org.docshare.test.TestORM3.testObject(TestORM3.java:38)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at junit.framework.TestCase.runTest(TestCase.java:168)
	at junit.framework.TestCase.runBare(TestCase.java:134)
	at junit.framework.TestResult$1.protect(TestResult.java:110)
	at junit.framework.TestResult.runProtected(TestResult.java:128)
	at junit.framework.TestResult.run(TestResult.java:113)
	at junit.framework.TestCase.run(TestCase.java:124)
	at junit.framework.TestSuite.runTest(TestSuite.java:243)
	at junit.framework.TestSuite.run(TestSuite.java:238)
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:83)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)

2018-02-12 09:06:55 [ERROR]-main - Log -Log.java(41)  -exec sql fail insert into `catalog`(`id`,`name`) values(?,?) ,param = 13,六爻_haha_haha_haha_haha_haha_haha
2018-02-12 09:06:55 [ERROR]-main - Log -Log.java(41)  -com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Duplicate entry '13' for key 1
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:39)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:27)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:513)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.Util.getInstance(Util.java:408)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:936)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3973)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3909)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2527)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2680)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2484)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1858)
	at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2079)
	at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2013)
	at com.mysql.jdbc.PreparedStatement.executeLargeUpdate(PreparedStatement.java:5104)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1998)
	at org.docshare.orm.DBHelper.updateWithArray(DBHelper.java:171)
	at org.docshare.orm.mysql.MySQLDelegate.save(MySQLDelegate.java:85)
	at org.docshare.orm.DBTool.save(DBTool.java:197)
	at org.docshare.orm.DBTool.save(DBTool.java:180)
	at org.docshare.orm.DBTool.save(DBTool.java:183)
	at org.docshare.test.TestORM3.testObject(TestORM3.java:38)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at junit.framework.TestCase.runTest(TestCase.java:168)
	at junit.framework.TestCase.runBare(TestCase.java:134)
	at junit.framework.TestResult$1.protect(TestResult.java:110)
	at junit.framework.TestResult.runProtected(TestResult.java:128)
	at junit.framework.TestResult.run(TestResult.java:113)
	at junit.framework.TestCase.run(TestCase.java:124)
	at junit.framework.TestSuite.runTest(TestSuite.java:243)
	at junit.framework.TestSuite.run(TestSuite.java:238)
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:83)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)

2018-02-12 09:06:55 [ERROR]-main - Log -Log.java(41)  -exec sql fail insert into `catalog`(`id`,`name`) values(?,?) ,param = 14,风水_haha_haha_haha_haha_haha_haha
2018-02-12 09:06:55 [ERROR]-main - Log -Log.java(41)  -com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Duplicate entry '14' for key 1
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:39)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:27)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:513)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.Util.getInstance(Util.java:408)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:936)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3973)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3909)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2527)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2680)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2484)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1858)
	at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2079)
	at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2013)
	at com.mysql.jdbc.PreparedStatement.executeLargeUpdate(PreparedStatement.java:5104)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1998)
	at org.docshare.orm.DBHelper.updateWithArray(DBHelper.java:171)
	at org.docshare.orm.mysql.MySQLDelegate.save(MySQLDelegate.java:85)
	at org.docshare.orm.DBTool.save(DBTool.java:197)
	at org.docshare.orm.DBTool.save(DBTool.java:180)
	at org.docshare.orm.DBTool.save(DBTool.java:183)
	at org.docshare.test.TestORM3.testObject(TestORM3.java:38)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at junit.framework.TestCase.runTest(TestCase.java:168)
	at junit.framework.TestCase.runBare(TestCase.java:134)
	at junit.framework.TestResult$1.protect(TestResult.java:110)
	at junit.framework.TestResult.runProtected(TestResult.java:128)
	at junit.framework.TestResult.run(TestResult.java:113)
	at junit.framework.TestCase.run(TestCase.java:124)
	at junit.framework.TestSuite.runTest(TestSuite.java:243)
	at junit.framework.TestSuite.run(TestSuite.java:238)
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:83)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)

2018-02-12 09:06:55 [ERROR]-main - Log -Log.java(41)  -exec sql fail insert into `catalog`(`id`,`name`) values(?,?) ,param = 15,房事_haha_haha_haha_haha_haha_haha
2018-02-12 09:06:55 [ERROR]-main - Log -Log.java(41)  -com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Duplicate entry '15' for key 1
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:39)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:27)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:513)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.Util.getInstance(Util.java:408)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:936)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3973)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3909)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2527)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2680)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2484)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1858)
	at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2079)
	at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2013)
	at com.mysql.jdbc.PreparedStatement.executeLargeUpdate(PreparedStatement.java:5104)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1998)
	at org.docshare.orm.DBHelper.updateWithArray(DBHelper.java:171)
	at org.docshare.orm.mysql.MySQLDelegate.save(MySQLDelegate.java:85)
	at org.docshare.orm.DBTool.save(DBTool.java:197)
	at org.docshare.orm.DBTool.save(DBTool.java:180)
	at org.docshare.orm.DBTool.save(DBTool.java:183)
	at org.docshare.test.TestORM3.testObject(TestORM3.java:38)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at junit.framework.TestCase.runTest(TestCase.java:168)
	at junit.framework.TestCase.runBare(TestCase.java:134)
	at junit.framework.TestResult$1.protect(TestResult.java:110)
	at junit.framework.TestResult.runProtected(TestResult.java:128)
	at junit.framework.TestResult.run(TestResult.java:113)
	at junit.framework.TestCase.run(TestCase.java:124)
	at junit.framework.TestSuite.runTest(TestSuite.java:243)
	at junit.framework.TestSuite.run(TestSuite.java:238)
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:83)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)

2018-02-12 09:06:55 [ERROR]-main - Log -Log.java(41)  -exec sql fail insert into `catalog`(`id`,`name`) values(?,?) ,param = 16,佛道_haha_haha_haha_haha_haha_haha
2018-02-12 09:06:55 [ERROR]-main - Log -Log.java(41)  -com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Duplicate entry '16' for key 1
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:39)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:27)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:513)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.Util.getInstance(Util.java:408)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:936)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3973)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3909)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2527)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2680)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2484)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1858)
	at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2079)
	at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2013)
	at com.mysql.jdbc.PreparedStatement.executeLargeUpdate(PreparedStatement.java:5104)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1998)
	at org.docshare.orm.DBHelper.updateWithArray(DBHelper.java:171)
	at org.docshare.orm.mysql.MySQLDelegate.save(MySQLDelegate.java:85)
	at org.docshare.orm.DBTool.save(DBTool.java:197)
	at org.docshare.orm.DBTool.save(DBTool.java:180)
	at org.docshare.orm.DBTool.save(DBTool.java:183)
	at org.docshare.test.TestORM3.testObject(TestORM3.java:38)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at junit.framework.TestCase.runTest(TestCase.java:168)
	at junit.framework.TestCase.runBare(TestCase.java:134)
	at junit.framework.TestResult$1.protect(TestResult.java:110)
	at junit.framework.TestResult.runProtected(TestResult.java:128)
	at junit.framework.TestResult.run(TestResult.java:113)
	at junit.framework.TestCase.run(TestCase.java:124)
	at junit.framework.TestSuite.runTest(TestSuite.java:243)
	at junit.framework.TestSuite.run(TestSuite.java:238)
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:83)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)

2018-02-12 09:06:55 [ERROR]-main - Log -Log.java(41)  -exec sql fail insert into `catalog`(`id`,`name`) values(?,?) ,param = 17,相术_haha_haha_haha_haha_haha_haha
2018-02-12 09:06:55 [ERROR]-main - Log -Log.java(41)  -com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Duplicate entry '17' for key 1
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:39)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:27)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:513)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.Util.getInstance(Util.java:408)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:936)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3973)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3909)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2527)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2680)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2484)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1858)
	at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2079)
	at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2013)
	at com.mysql.jdbc.PreparedStatement.executeLargeUpdate(PreparedStatement.java:5104)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1998)
	at org.docshare.orm.DBHelper.updateWithArray(DBHelper.java:171)
	at org.docshare.orm.mysql.MySQLDelegate.save(MySQLDelegate.java:85)
	at org.docshare.orm.DBTool.save(DBTool.java:197)
	at org.docshare.orm.DBTool.save(DBTool.java:180)
	at org.docshare.orm.DBTool.save(DBTool.java:183)
	at org.docshare.test.TestORM3.testObject(TestORM3.java:38)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at junit.framework.TestCase.runTest(TestCase.java:168)
	at junit.framework.TestCase.runBare(TestCase.java:134)
	at junit.framework.TestResult$1.protect(TestResult.java:110)
	at junit.framework.TestResult.runProtected(TestResult.java:128)
	at junit.framework.TestResult.run(TestResult.java:113)
	at junit.framework.TestCase.run(TestCase.java:124)
	at junit.framework.TestSuite.runTest(TestSuite.java:243)
	at junit.framework.TestSuite.run(TestSuite.java:238)
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:83)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)

2018-02-12 09:06:55 [ERROR]-main - Log -Log.java(41)  -exec sql fail insert into `catalog`(`id`,`name`) values(?,?) ,param = 18,八字_haha_haha_haha_haha_haha_haha
2018-02-12 09:06:55 [ERROR]-main - Log -Log.java(41)  -com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Duplicate entry '18' for key 1
	at sun.reflect.GeneratedConstructorAccessor5.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:27)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:513)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.Util.getInstance(Util.java:408)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:936)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3973)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3909)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2527)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2680)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2484)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1858)
	at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2079)
	at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2013)
	at com.mysql.jdbc.PreparedStatement.executeLargeUpdate(PreparedStatement.java:5104)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1998)
	at org.docshare.orm.DBHelper.updateWithArray(DBHelper.java:171)
	at org.docshare.orm.mysql.MySQLDelegate.save(MySQLDelegate.java:85)
	at org.docshare.orm.DBTool.save(DBTool.java:197)
	at org.docshare.orm.DBTool.save(DBTool.java:180)
	at org.docshare.orm.DBTool.save(DBTool.java:183)
	at org.docshare.test.TestORM3.testObject(TestORM3.java:38)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at junit.framework.TestCase.runTest(TestCase.java:168)
	at junit.framework.TestCase.runBare(TestCase.java:134)
	at junit.framework.TestResult$1.protect(TestResult.java:110)
	at junit.framework.TestResult.runProtected(TestResult.java:128)
	at junit.framework.TestResult.run(TestResult.java:113)
	at junit.framework.TestCase.run(TestCase.java:124)
	at junit.framework.TestSuite.runTest(TestSuite.java:243)
	at junit.framework.TestSuite.run(TestSuite.java:238)
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:83)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)

2018-02-12 09:06:55 [ INFO]-main - Log -Log.java(30)  -DBTool run :delete from book where id >909  param=[]
2018-02-12 09:06:55 [ERROR]-main - Log -Log.java(41)  -setup
2018-02-12 09:06:55 [ INFO]-main - Log -Log.java(30)  -DBTool run :delete from book where id >909  param=[]
2018-02-12 09:06:55 [ERROR]-main - Log -Log.java(41)  -setup
2018-02-12 09:06:55 [ INFO]-main - Log -Log.java(30)  -DBTool run :delete from book where id >909  param=[]
2018-02-12 09:08:04 [ERROR]-main - Log -Log.java(41)  -setup
2018-02-12 09:11:10 [ERROR]-main - Log -Log.java(41)  -setup
2018-02-12 09:16:24 [ERROR]-main - Log -Log.java(41)  -setup
2018-02-12 09:16:36 [ INFO]-main - Log -Log.java(30)  -DBTool run :delete from book where id >909  param=[]
2018-02-12 09:16:36 [ERROR]-main - Log -Log.java(41)  -setup
2018-02-12 09:37:31 [ERROR]-main - Log -Log.java(41)  -exec sql fail insert into `select`() values() ,param = 
2018-02-12 09:37:31 [ERROR]-main - Log -Log.java(41)  -com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Table '621m.select' doesn't exist
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:39)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:27)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:513)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.Util.getInstance(Util.java:408)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:944)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3973)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3909)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2527)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2680)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2484)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1858)
	at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2079)
	at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2013)
	at com.mysql.jdbc.PreparedStatement.executeLargeUpdate(PreparedStatement.java:5104)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1998)
	at org.docshare.orm.DBHelper.updateWithArray(DBHelper.java:171)
	at org.docshare.orm.mysql.MySQLDelegate.save(MySQLDelegate.java:85)
	at org.docshare.orm.DBTool.save(DBTool.java:204)
	at org.docshare.orm.DBTool.save(DBTool.java:178)
	at org.docshare.orm.Model.save(Model.java:347)
	at org.docshare.test.TestORMFoo.testInsert(TestORMFoo.java:18)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at junit.framework.TestCase.runTest(TestCase.java:168)
	at junit.framework.TestCase.runBare(TestCase.java:134)
	at junit.framework.TestResult$1.protect(TestResult.java:110)
	at junit.framework.TestResult.runProtected(TestResult.java:128)
	at junit.framework.TestResult.run(TestResult.java:113)
	at junit.framework.TestCase.run(TestCase.java:124)
	at junit.framework.TestSuite.runTest(TestSuite.java:243)
	at junit.framework.TestSuite.run(TestSuite.java:238)
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:83)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)

2018-02-12 09:37:31 [ERROR]-main - Log -Log.java(41)  -com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Table '621m.select' doesn't exist
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:39)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:27)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:513)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.Util.getInstance(Util.java:408)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:944)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3973)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3909)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2527)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2680)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2484)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1858)
	at com.mysql.jdbc.PreparedStatement.executeQuery(PreparedStatement.java:1966)
	at org.docshare.orm.DBHelper.getPrepareRS(DBHelper.java:115)
	at org.docshare.orm.mysql.MySQLDelegate.resultById(MySQLDelegate.java:24)
	at org.docshare.orm.DBTool.get(DBTool.java:125)
	at org.docshare.orm.DBTool.get(DBTool.java:114)
	at org.docshare.test.TestORMFoo.testUpdate(TestORMFoo.java:24)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at junit.framework.TestCase.runTest(TestCase.java:168)
	at junit.framework.TestCase.runBare(TestCase.java:134)
	at junit.framework.TestResult$1.protect(TestResult.java:110)
	at junit.framework.TestResult.runProtected(TestResult.java:128)
	at junit.framework.TestResult.run(TestResult.java:113)
	at junit.framework.TestCase.run(TestCase.java:124)
	at junit.framework.TestSuite.runTest(TestSuite.java:243)
	at junit.framework.TestSuite.run(TestSuite.java:238)
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:83)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)

2018-02-12 09:37:31 [ERROR]-main - Log -Log.java(41)  -exec sql fail delete from `select` where `ss` = ? ,param = 0
2018-02-12 09:37:31 [ERROR]-main - Log -Log.java(41)  -com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Table '621m.select' doesn't exist
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:39)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:27)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:513)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.Util.getInstance(Util.java:408)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:944)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3973)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3909)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2527)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2680)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2484)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1858)
	at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2079)
	at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2013)
	at com.mysql.jdbc.PreparedStatement.executeLargeUpdate(PreparedStatement.java:5104)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1998)
	at org.docshare.orm.DBHelper.updateWithArray(DBHelper.java:171)
	at org.docshare.orm.DBHelper.update(DBHelper.java:190)
	at org.docshare.orm.mysql.MySQLDelegate.delete(MySQLDelegate.java:98)
	at org.docshare.orm.DBTool.del(DBTool.java:259)
	at org.docshare.test.TestORMFoo.testRemove(TestORMFoo.java:29)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at junit.framework.TestCase.runTest(TestCase.java:168)
	at junit.framework.TestCase.runBare(TestCase.java:134)
	at junit.framework.TestResult$1.protect(TestResult.java:110)
	at junit.framework.TestResult.runProtected(TestResult.java:128)
	at junit.framework.TestResult.run(TestResult.java:113)
	at junit.framework.TestCase.run(TestCase.java:124)
	at junit.framework.TestSuite.runTest(TestSuite.java:243)
	at junit.framework.TestSuite.run(TestSuite.java:238)
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:83)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)

2018-02-12 09:37:31 [ERROR]-main - Log -Log.java(41)  -com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Table '621m.select' doesn't exist
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:39)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:27)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:513)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.Util.getInstance(Util.java:408)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:944)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3973)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3909)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2527)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2680)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2484)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1858)
	at com.mysql.jdbc.PreparedStatement.executeQuery(PreparedStatement.java:1966)
	at org.docshare.orm.DBHelper.getPrepareRS(DBHelper.java:115)
	at org.docshare.orm.mysql.MySQLDelegate.resultById(MySQLDelegate.java:24)
	at org.docshare.orm.DBTool.get(DBTool.java:125)
	at org.docshare.orm.DBTool.get(DBTool.java:114)
	at org.docshare.test.TestORMFoo.testRemove(TestORMFoo.java:30)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at junit.framework.TestCase.runTest(TestCase.java:168)
	at junit.framework.TestCase.runBare(TestCase.java:134)
	at junit.framework.TestResult$1.protect(TestResult.java:110)
	at junit.framework.TestResult.runProtected(TestResult.java:128)
	at junit.framework.TestResult.run(TestResult.java:113)
	at junit.framework.TestCase.run(TestCase.java:124)
	at junit.framework.TestSuite.runTest(TestSuite.java:243)
	at junit.framework.TestSuite.run(TestSuite.java:238)
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:83)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)

2018-02-12 09:38:21 [ERROR]-main - Log -Log.java(41)  -setup
2018-02-12 09:38:21 [ERROR]-main - Log -Log.java(41)  -setup
2018-02-12 09:38:21 [ERROR]-main - Log -Log.java(41)  -setup
2018-02-12 09:39:05 [ERROR]-main - Log -Log.java(41)  -setup
2018-02-12 09:41:06 [ERROR]-main - Log -Log.java(41)  -setup
2018-02-12 09:41:34 [ERROR]-main - Log -Log.java(41)  -setup
2018-02-12 09:41:34 [ERROR]-main - Log -Log.java(41)  -setup
2018-02-12 09:41:34 [ERROR]-main - Log -Log.java(41)  -setup
2018-02-12 09:41:44 [ERROR]-main - Log -Log.java(41)  -setup
2018-02-12 09:41:44 [ERROR]-main - Log -Log.java(41)  -setup
2018-02-12 09:41:44 [ERROR]-main - Log -Log.java(41)  -setup
2018-02-14 17:29:40 [ERROR]-main - Log -Log.java(41)  -setup
2018-02-14 17:30:04 [ERROR]-main - Log -Log.java(41)  -setup
2018-02-14 17:30:19 [ERROR]-main - Log -Log.java(41)  -setup
2018-02-14 17:32:48 [ERROR]-main - Log -Log.java(41)  -setup
2018-02-15 13:28:41 [ERROR]-main - Log -Log.java(41)  -setup
2018-02-15 13:28:51 [ERROR]-main - Log -Log.java(41)  -setup
2018-02-15 13:28:51 [ INFO]-main - Log -Log.java(30)  -Model[limit=ll,update=wuwu,id=1,order=oo,select=haha,delete=dd,group=gg]
2018-02-18 16:37:01 [ERROR]-main - Log -Log.java(41)  -setup
2018-02-18 16:37:02 [ INFO]-main - Log -Log.java(30)  -[{"about":" ","author":"haha","catalog_id":1,"chaodai":"清  ","cname":"本草_haha_haha","file_name":"000-神农本草经.txt","id":1,"name":"神农本草经","tm_year":"公元1644-1911年  ","type":"txt"},{"about":" ","author":"haha","catalog_id":1,"chaodai":"清  ","cname":"方剂","file_name":"000-神农本草经.txt","id":1,"name":"神农本草经","tm_year":"公元1644-1911年  ","type":"txt"},{"about":" ","author":"haha","catalog_id":1,"chaodai":"清  ","cname":"医案","file_name":"000-神农本草经.txt","id":1,"name":"神农本草经","tm_year":"公元1644-1911年  ","type":"txt"},{"about":" ","author":"haha","catalog_id":1,"chaodai":"清  ","cname":"经论_haha_haha_haha_haha_haha_haha","file_name":"000-神农本草经.txt","id":1,"name":"神农本草经","tm_year":"公元1644-1911年  ","type":"txt"},{"about":" ","author":"haha","catalog_id":1,"chaodai":"清  ","cname":"专科_haha_haha_haha_haha_haha_haha","file_name":"000-神农本草经.txt","id":1,"name":"神农本草经","tm_year":"公元1644-1911年  ","type":"txt"}]
2018-02-18 16:41:10 [ERROR]-main - Log -Log.java(41)  -setup
2018-02-18 16:41:11 [ INFO]-main - Log -Log.java(30)  -[
	{
		"about":" ",
		"author":"haha",
		"catalog_id":1,
		"chaodai":"清  ",
		"cname":"本草_haha_haha",
		"file_name":"000-神农本草经.txt",
		"id":1,
		"name":"神农本草经",
		"tm_year":"公元1644-1911年  ",
		"type":"txt"
	},
	{
		"about":" ",
		"author":"haha",
		"catalog_id":1,
		"chaodai":"清  ",
		"cname":"方剂",
		"file_name":"000-神农本草经.txt",
		"id":1,
		"name":"神农本草经",
		"tm_year":"公元1644-1911年  ",
		"type":"txt"
	},
	{
		"about":" ",
		"author":"haha",
		"catalog_id":1,
		"chaodai":"清  ",
		"cname":"医案",
		"file_name":"000-神农本草经.txt",
		"id":1,
		"name":"神农本草经",
		"tm_year":"公元1644-1911年  ",
		"type":"txt"
	},
	{
		"about":" ",
		"author":"haha",
		"catalog_id":1,
		"chaodai":"清  ",
		"cname":"经论_haha_haha_haha_haha_haha_haha",
		"file_name":"000-神农本草经.txt",
		"id":1,
		"name":"神农本草经",
		"tm_year":"公元1644-1911年  ",
		"type":"txt"
	},
	{
		"about":" ",
		"author":"haha",
		"catalog_id":1,
		"chaodai":"清  ",
		"cname":"专科_haha_haha_haha_haha_haha_haha",
		"file_name":"000-神农本草经.txt",
		"id":1,
		"name":"神农本草经",
		"tm_year":"公元1644-1911年  ",
		"type":"txt"
	}
]
2018-04-20 10:21:59 [ERROR]-main - Log -Log.java(41)  -com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:39)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:27)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:513)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.SQLError.createCommunicationsException(SQLError.java:990)
	at com.mysql.jdbc.MysqlIO.<init>(MysqlIO.java:341)
	at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2186)
	at com.mysql.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:2219)
	at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2014)
	at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:776)
	at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:47)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:39)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:27)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:513)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:386)
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:330)
	at java.sql.DriverManager.getConnection(DriverManager.java:582)
	at java.sql.DriverManager.getConnection(DriverManager.java:185)
	at org.docshare.orm.DBHelper.conn(DBHelper.java:72)
	at org.docshare.orm.DBHelper.listColumn(DBHelper.java:259)
	at org.docshare.orm.mysql.MySQLDelegate.listColumn(MySQLDelegate.java:293)
	at org.docshare.orm.DBTool.<init>(DBTool.java:43)
	at org.docshare.orm.DBTool.getIns(DBTool.java:307)
	at org.docshare.orm.Model.tool(Model.java:37)
	at org.docshare.test.TestORM2.setUp(TestORM2.java:18)
	at junit.framework.TestCase.runBare(TestCase.java:132)
	at junit.framework.TestResult$1.protect(TestResult.java:110)
	at junit.framework.TestResult.runProtected(TestResult.java:128)
	at junit.framework.TestResult.run(TestResult.java:113)
	at junit.framework.TestCase.run(TestCase.java:124)
	at junit.framework.TestSuite.runTest(TestSuite.java:243)
	at junit.framework.TestSuite.run(TestSuite.java:238)
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:83)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)
Caused by: java.net.ConnectException: Connection refused: connect
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.PlainSocketImpl.doConnect(PlainSocketImpl.java:333)
	at java.net.PlainSocketImpl.connectToAddress(PlainSocketImpl.java:195)
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:182)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:366)
	at java.net.Socket.connect(Socket.java:519)
	at com.mysql.jdbc.StandardSocketFactory.connect(StandardSocketFactory.java:211)
	at com.mysql.jdbc.MysqlIO.<init>(MysqlIO.java:300)
	... 35 more

2018-04-20 10:21:59 [ERROR]-main - Log -Log.java(41)  -Config [dbhost=localhost, dbname=mvc_demo, dbusr=root, dbpwd=123456, port = 3306, tpl_base=null, ctr_base=null,reloadable=true]
2018-04-20 10:22:01 [ERROR]-main - Log -Log.java(41)  -com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:39)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:27)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:513)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.SQLError.createCommunicationsException(SQLError.java:990)
	at com.mysql.jdbc.MysqlIO.<init>(MysqlIO.java:341)
	at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2186)
	at com.mysql.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:2219)
	at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2014)
	at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:776)
	at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:47)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:39)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:27)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:513)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:386)
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:330)
	at java.sql.DriverManager.getConnection(DriverManager.java:582)
	at java.sql.DriverManager.getConnection(DriverManager.java:185)
	at org.docshare.orm.DBHelper.conn(DBHelper.java:72)
	at org.docshare.orm.DBHelper.listColumn(DBHelper.java:259)
	at org.docshare.orm.mysql.MySQLDelegate.listColumn(MySQLDelegate.java:293)
	at org.docshare.orm.DBTool.<init>(DBTool.java:43)
	at org.docshare.orm.DBTool.getIns(DBTool.java:307)
	at org.docshare.orm.Model.tool(Model.java:37)
	at org.docshare.test.TestORM2.setUp(TestORM2.java:18)
	at junit.framework.TestCase.runBare(TestCase.java:132)
	at junit.framework.TestResult$1.protect(TestResult.java:110)
	at junit.framework.TestResult.runProtected(TestResult.java:128)
	at junit.framework.TestResult.run(TestResult.java:113)
	at junit.framework.TestCase.run(TestCase.java:124)
	at junit.framework.TestSuite.runTest(TestSuite.java:243)
	at junit.framework.TestSuite.run(TestSuite.java:238)
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:83)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)
Caused by: java.net.ConnectException: Connection refused: connect
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.PlainSocketImpl.doConnect(PlainSocketImpl.java:333)
	at java.net.PlainSocketImpl.connectToAddress(PlainSocketImpl.java:195)
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:182)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:366)
	at java.net.Socket.connect(Socket.java:519)
	at com.mysql.jdbc.StandardSocketFactory.connect(StandardSocketFactory.java:211)
	at com.mysql.jdbc.MysqlIO.<init>(MysqlIO.java:300)
	... 35 more

2018-04-20 10:22:01 [ERROR]-main - Log -Log.java(41)  -Config [dbhost=localhost, dbname=mvc_demo, dbusr=root, dbpwd=123456, port = 3306, tpl_base=null, ctr_base=null,reloadable=true]
2018-04-20 10:22:03 [ERROR]-main - Log -Log.java(41)  -com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:39)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:27)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:513)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.SQLError.createCommunicationsException(SQLError.java:990)
	at com.mysql.jdbc.MysqlIO.<init>(MysqlIO.java:341)
	at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2186)
	at com.mysql.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:2219)
	at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2014)
	at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:776)
	at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:47)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:39)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:27)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:513)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:386)
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:330)
	at java.sql.DriverManager.getConnection(DriverManager.java:582)
	at java.sql.DriverManager.getConnection(DriverManager.java:185)
	at org.docshare.orm.DBHelper.conn(DBHelper.java:72)
	at org.docshare.orm.DBHelper.listColumn(DBHelper.java:259)
	at org.docshare.orm.mysql.MySQLDelegate.listColumn(MySQLDelegate.java:293)
	at org.docshare.orm.DBTool.<init>(DBTool.java:43)
	at org.docshare.orm.DBTool.getIns(DBTool.java:307)
	at org.docshare.orm.Model.tool(Model.java:37)
	at org.docshare.test.TestORM2.setUp(TestORM2.java:18)
	at junit.framework.TestCase.runBare(TestCase.java:132)
	at junit.framework.TestResult$1.protect(TestResult.java:110)
	at junit.framework.TestResult.runProtected(TestResult.java:128)
	at junit.framework.TestResult.run(TestResult.java:113)
	at junit.framework.TestCase.run(TestCase.java:124)
	at junit.framework.TestSuite.runTest(TestSuite.java:243)
	at junit.framework.TestSuite.run(TestSuite.java:238)
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:83)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)
Caused by: java.net.ConnectException: Connection refused: connect
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.PlainSocketImpl.doConnect(PlainSocketImpl.java:333)
	at java.net.PlainSocketImpl.connectToAddress(PlainSocketImpl.java:195)
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:182)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:366)
	at java.net.Socket.connect(Socket.java:519)
	at com.mysql.jdbc.StandardSocketFactory.connect(StandardSocketFactory.java:211)
	at com.mysql.jdbc.MysqlIO.<init>(MysqlIO.java:300)
	... 35 more

2018-04-20 10:22:03 [ERROR]-main - Log -Log.java(41)  -Config [dbhost=localhost, dbname=mvc_demo, dbusr=root, dbpwd=123456, port = 3306, tpl_base=null, ctr_base=null,reloadable=true]
2018-04-20 10:23:24 [ INFO]-main - Log -Log.java(30)  -DBTool run :delete from book where id >909  param=[]
2018-04-20 10:26:02 [ INFO]-main - Log -Log.java(30)  -DBTool run :delete from book where id >909  param=[]
2018-05-02 20:36:49 [ERROR]-main - Log -Log.java(41)  -com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:39)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:27)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:513)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.SQLError.createCommunicationsException(SQLError.java:990)
	at com.mysql.jdbc.MysqlIO.<init>(MysqlIO.java:341)
	at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2186)
	at com.mysql.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:2219)
	at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2014)
	at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:776)
	at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:47)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:39)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:27)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:513)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:386)
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:330)
	at java.sql.DriverManager.getConnection(DriverManager.java:582)
	at java.sql.DriverManager.getConnection(DriverManager.java:185)
	at org.docshare.orm.DBHelper.conn(DBHelper.java:71)
	at org.docshare.orm.DBHelper.keyColumn(DBHelper.java:288)
	at org.docshare.orm.mysql.MySQLDelegate.keyColumn(MySQLDelegate.java:298)
	at org.docshare.orm.DBTool.<init>(DBTool.java:50)
	at org.docshare.orm.DBTool.getIns(DBTool.java:301)
	at org.docshare.orm.Model.tool(Model.java:37)
	at org.docshare.orm.LasyList.<init>(LasyList.java:37)
	at org.docshare.orm.LasyList.fromRawSql(LasyList.java:443)
	at org.docshare.test.TestRawSQL.test(TestRawSQL.java:16)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:44)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:41)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20)
	at org.junit.runners.BlockJUnit4ClassRunner.runNotIgnored(BlockJUnit4ClassRunner.java:79)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:71)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:49)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:193)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:52)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:191)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:42)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:184)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:236)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)
Caused by: java.net.ConnectException: Connection refused: connect
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.PlainSocketImpl.doConnect(PlainSocketImpl.java:333)
	at java.net.PlainSocketImpl.connectToAddress(PlainSocketImpl.java:195)
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:182)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:366)
	at java.net.Socket.connect(Socket.java:519)
	at com.mysql.jdbc.StandardSocketFactory.connect(StandardSocketFactory.java:211)
	at com.mysql.jdbc.MysqlIO.<init>(MysqlIO.java:300)
	... 46 more

2018-05-02 20:36:49 [ERROR]-main - Log -Log.java(41)  -Config [dbhost=localhost, dbname=mvc_demo, dbusr=root, dbpwd=123456, port = 3306, tpl_base=null, ctr_base=null,reloadable=true,useSSL=false]
2018-05-02 21:22:29 [ERROR]-main - Log -Log.java(41)  -setup
2018-05-02 21:22:29 [ INFO]-main - Log -Log.java(30)  -m = null
2018-05-02 21:22:29 [ INFO]-main - Log -Log.java(30)  -DBTool run :delete from book where id >909  param=[]
2018-05-02 21:22:29 [ERROR]-main - Log -Log.java(41)  -setup
2018-05-02 21:22:29 [ INFO]-main - Log -Log.java(30)  -DBTool run :delete from book where id >909  param=[]
2018-05-02 21:22:29 [ERROR]-main - Log -Log.java(41)  -setup
2018-05-02 21:22:29 [ERROR]-main - Log -Log.java(41)  -testOrder
2018-05-02 21:22:29 [ INFO]-main - Log -Log.java(30)  -Model[id=909,author=null,chaodai=null,name=ss,about=null,type=null,file_name=null,tm_year=null,catalog_id=1]
2018-05-02 21:22:29 [ INFO]-main - Log -Log.java(30)  -DBTool run :delete from book where id >909  param=[]
2018-05-02 21:22:29 [ERROR]-main - Log -Log.java(41)  -setup
2018-05-02 21:22:29 [ERROR]-main - Log -Log.java(41)  -test update
2018-05-02 21:22:29 [ INFO]-main - Log -Log.java(30)  -DBTool run :update book set author=? where id = ?  param=[haha,1]
2018-05-02 21:22:29 [ INFO]-main - Log -Log.java(30)  -1
2018-05-02 21:22:29 [ INFO]-main - Log -Log.java(30)  -DBTool run :delete from book where id >909  param=[]
2018-05-02 21:22:29 [ERROR]-main - Log -Log.java(41)  -setup
2018-05-02 21:22:29 [ERROR]-main - Log -Log.java(41)  -testDel
2018-05-02 21:22:29 [ INFO]-main - Log -Log.java(30)  -m is delete ?no exist
2018-05-02 21:22:29 [ INFO]-main - Log -Log.java(30)  -no change data for update update `book` set  where id=4
2018-05-02 21:22:29 [ INFO]-main - Log -Log.java(30)  -DBTool run :delete from book where id >909  param=[]
2018-05-02 21:22:29 [ERROR]-main - Log -Log.java(41)  -setup
2018-05-02 21:22:29 [ERROR]-main - Log -Log.java(41)  -testInsert
2018-05-02 21:22:29 [ INFO]-main - Log -Log.java(30)  -insert return 1
2018-05-02 21:22:29 [ INFO]-main - Log -Log.java(30)  -DBTool run :delete from book where id >909  param=[]
2018-05-02 21:22:29 [ERROR]-main - Log -Log.java(41)  -setup
2018-05-02 21:22:29 [ERROR]-main - Log -Log.java(41)  -testInsert
2018-05-02 21:22:29 [ INFO]-main - Log -Log.java(30)  -Model[id=909,author=null,chaodai=null,name=ss,about=null,type=null,file_name=null,tm_year=null,catalog_id=1]
2018-05-02 21:22:29 [ INFO]-main - Log -Log.java(30)  -DBTool run :delete from book where id >909  param=[]
2018-05-02 21:22:29 [ERROR]-main - Log -Log.java(41)  -setup
2018-05-02 21:22:29 [ERROR]-main - Log -Log.java(41)  -testExtra
2018-05-02 21:22:29 [ INFO]-main - Log -Log.java(30)  -Model[id=1,author=haha,chaodai=清  ,name=神农本草经,about= ,type=txt,file_name=000-神农本草经.txt,tm_year=公元1644-1911年  ,catalog_id=1,extra={"haha":"sfsf"}]
2018-05-02 21:22:29 [ INFO]-main - Log -Log.java(30)  -haha = sfsf
2018-05-02 21:22:29 [ INFO]-main - Log -Log.java(30)  -DBTool run :delete from book where id >909  param=[]
2018-05-02 21:22:29 [ERROR]-main - Log -Log.java(41)  -setup
2018-05-02 21:22:29 [ERROR]-main - Log -Log.java(41)  -testGet
2018-05-02 21:22:29 [ INFO]-main - Log -Log.java(30)  -Model[id=1,author=haha,chaodai=清  ,name=神农本草经,about= ,type=txt,file_name=000-神农本草经.txt,tm_year=公元1644-1911年  ,catalog_id=1]
2018-05-02 21:22:29 [ INFO]-main - Log -Log.java(30)  -DBTool run :delete from book where id >909  param=[]
2018-05-02 21:22:29 [ERROR]-main - Log -Log.java(41)  -setup
2018-05-02 21:22:29 [ERROR]-main - Log -Log.java(41)  -testAll
2018-05-02 21:22:29 [ INFO]-main - Log -Log.java(30)  -result1 887
2018-05-02 21:22:29 [ INFO]-main - Log -Log.java(30)  -Model[id=2,author=吴普  ,chaodai=魏晋  ,name=haha,about= ,type=txt,file_name=001-吴普本草.txt,tm_year=公元420年—589  ,catalog_id=1]
2018-05-02 21:22:29 [ INFO]-main - Log -Log.java(30)  -DBTool run :delete from book where id >909  param=[]
2018-05-02 21:22:29 [ERROR]-main - Log -Log.java(41)  -setup
2018-05-02 21:22:29 [ERROR]-main - Log -Log.java(41)  -testCustom
2018-05-02 21:22:29 [ INFO]-main - Log -Log.java(30)  -result2 30
2018-05-02 21:22:29 [ INFO]-main - Log -Log.java(30)  -Model[id=32,author=张秉成  ,chaodai=清  ,name=本草便读,about= ,file_name=031-本草便读.txt,type=txt,tm_year=公元1644-1911年  ,catalog_id=1]
2018-05-02 21:22:29 [ INFO]-main - Log -Log.java(30)  -DBTool run :delete from book where id >909  param=[]
2018-05-02 21:22:29 [ERROR]-main - Log -Log.java(41)  -setup
2018-05-02 21:22:29 [ERROR]-main - Log -Log.java(41)  -testEq
2018-05-02 21:22:29 [ INFO]-main - Log -Log.java(30)  -[Model[id=12,author=刘文泰,chaodai=明,name=本草品汇精要,about=,type=txt,file_name=,tm_year=1503,catalog_id=1]]
2018-05-02 21:22:29 [ INFO]-main - Log -Log.java(30)  -[]
2018-05-02 21:22:29 [ INFO]-main - Log -Log.java(30)  -[]
2018-05-02 21:22:29 [ INFO]-main - Log -Log.java(30)  -DBTool run :delete from book where id >909  param=[]
2018-05-02 21:22:29 [ERROR]-main - Log -Log.java(41)  -setup
2018-05-02 21:22:29 [ERROR]-main - Log -Log.java(41)  -testByExample
2018-05-02 21:22:29 [ INFO]-main - Log -Log.java(30)  -1
2018-05-02 21:22:29 [ INFO]-main - Log -Log.java(30)  -[Model[id=12,author=刘文泰,chaodai=明,name=本草品汇精要,about=,type=txt,file_name=,tm_year=1503,catalog_id=1]]
2018-05-02 21:22:29 [ INFO]-main - Log -Log.java(30)  -DBTool run :delete from book where id >909  param=[]
2018-05-02 21:22:29 [ERROR]-main - Log -Log.java(41)  -setup
2018-05-02 21:22:29 [ INFO]-main - Log -Log.java(30)  -DBTool run :delete from book where id >909  param=[]
2018-05-21 10:54:29 [ERROR]-main - Log -Log.java(41)  -com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Unknown database '621m'
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:39)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:27)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:513)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.Util.getInstance(Util.java:408)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:944)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3973)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3909)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:873)
	at com.mysql.jdbc.MysqlIO.secureAuth411(MysqlIO.java:4420)
	at com.mysql.jdbc.MysqlIO.doHandshake(MysqlIO.java:1278)
	at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2188)
	at com.mysql.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:2219)
	at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2014)
	at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:776)
	at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:47)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:39)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:27)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:513)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:386)
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:330)
	at java.sql.DriverManager.getConnection(DriverManager.java:582)
	at java.sql.DriverManager.getConnection(DriverManager.java:185)
	at org.docshare.orm.DBHelper.conn(DBHelper.java:71)
	at org.docshare.orm.DBHelper.listColumn(DBHelper.java:268)
	at org.docshare.orm.mysql.MySQLDelegate.listColumn(MySQLDelegate.java:293)
	at org.docshare.orm.DBTool.<init>(DBTool.java:43)
	at org.docshare.orm.DBTool.getIns(DBTool.java:307)
	at org.docshare.orm.Model.tool(Model.java:37)
	at org.docshare.test.TestTransaction.test(TestTransaction.java:11)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at junit.framework.TestCase.runTest(TestCase.java:168)
	at junit.framework.TestCase.runBare(TestCase.java:134)
	at junit.framework.TestResult$1.protect(TestResult.java:110)
	at junit.framework.TestResult.runProtected(TestResult.java:128)
	at junit.framework.TestResult.run(TestResult.java:113)
	at junit.framework.TestCase.run(TestCase.java:124)
	at junit.framework.TestSuite.runTest(TestSuite.java:243)
	at junit.framework.TestSuite.run(TestSuite.java:238)
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:83)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)

2018-05-21 10:54:29 [ERROR]-main - Log -Log.java(41)  -Config [dbhost=localhost, dbname=621m, dbusr=root, dbpwd=123456, port = 3306, tpl_base=null, ctr_base=null,reloadable=true,useSSL=false,interceptors={}]
2018-06-12 21:51:45 [ERROR]-main - Log -Log.java(41)  -org.postgresql.util.PSQLException: Connection to localhost:3306 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:245)
	at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:49)
	at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:195)
	at org.postgresql.Driver.makeConnection(Driver.java:452)
	at org.postgresql.Driver.connect(Driver.java:254)
	at java.sql.DriverManager.getConnection(DriverManager.java:582)
	at java.sql.DriverManager.getConnection(DriverManager.java:185)
	at org.docshare.orm.postgres.PostgresDBHelper.conn(PostgresDBHelper.java:35)
	at org.docshare.orm.postgres.PostgresDBHelper.main(PostgresDBHelper.java:49)
Caused by: java.net.ConnectException: Connection refused: connect
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.PlainSocketImpl.doConnect(PlainSocketImpl.java:333)
	at java.net.PlainSocketImpl.connectToAddress(PlainSocketImpl.java:195)
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:182)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:366)
	at java.net.Socket.connect(Socket.java:519)
	at org.postgresql.core.PGStream.<init>(PGStream.java:69)
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:156)
	... 8 more

2018-06-12 21:51:45 [ERROR]-main - Log -Log.java(41)  -Config [dbhost=localhost, dbname=621m, dbusr=root, dbpwd=123456, port = 3306, tpl_base=null, ctr_base=null,reloadable=true,useSSL=false,interceptors={}]
2018-06-12 21:51:46 [ERROR]-main - Log -Log.java(41)  -org.postgresql.util.PSQLException: Connection to localhost:3306 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:245)
	at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:49)
	at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:195)
	at org.postgresql.Driver.makeConnection(Driver.java:452)
	at org.postgresql.Driver.connect(Driver.java:254)
	at java.sql.DriverManager.getConnection(DriverManager.java:582)
	at java.sql.DriverManager.getConnection(DriverManager.java:185)
	at org.docshare.orm.postgres.PostgresDBHelper.conn(PostgresDBHelper.java:35)
	at org.docshare.orm.DBHelper.getRS(DBHelper.java:127)
	at org.docshare.orm.postgres.PostgresDBHelper.main(PostgresDBHelper.java:50)
Caused by: java.net.ConnectException: Connection refused: connect
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.PlainSocketImpl.doConnect(PlainSocketImpl.java:333)
	at java.net.PlainSocketImpl.connectToAddress(PlainSocketImpl.java:195)
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:182)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:366)
	at java.net.Socket.connect(Socket.java:519)
	at org.postgresql.core.PGStream.<init>(PGStream.java:69)
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:156)
	... 9 more

2018-06-12 21:51:46 [ERROR]-main - Log -Log.java(41)  -Config [dbhost=localhost, dbname=621m, dbusr=root, dbpwd=123456, port = 3306, tpl_base=null, ctr_base=null,reloadable=true,useSSL=false,interceptors={}]
2018-06-12 22:20:47 [ INFO]-main - Log -Log.java(30)  -{"asc_or_desc":{"name":"asc_or_desc","remark":"asc_or_desc","tb":"","type":12},"cardinality":{"name":"cardinality","remark":"cardinality","tb":"pg_class","type":7},"column_name":{"name":"column_name","remark":"column_name","tb":"","type":12},"filter_condition":{"name":"filter_condition","remark":"filter_condition","tb":"","type":12},"index_name":{"name":"index_name","remark":"index_name","tb":"pg_class","type":12},"index_qualifier":{"name":"index_qualifier","remark":"index_qualifier","tb":"","type":12},"non_unique":{"name":"non_unique","remark":"non_unique","tb":"","type":-7},"ordinal_position":{"name":"ordinal_position","remark":"ordinal_position","tb":"","type":4},"pages":{"name":"pages","remark":"pages","tb":"pg_class","type":4},"table_cat":{"name":"table_cat","remark":"table_cat","tb":"","type":12},"table_name":{"name":"table_name","remark":"table_name","tb":"pg_class","type":12},"table_schem":{"name":"table_schem","remark":"table_schem","tb":"pg_namespace","type":12},"type":{"name":"type","remark":"type","tb":"","type":4}}
2018-06-12 22:21:12 [ INFO]-main - Log -Log.java(30)  -{
	"asc_or_desc":{
		"name":"asc_or_desc",
		"remark":"asc_or_desc",
		"tb":"",
		"type":12
	},
	"cardinality":{
		"name":"cardinality",
		"remark":"cardinality",
		"tb":"pg_class",
		"type":7
	},
	"column_name":{
		"name":"column_name",
		"remark":"column_name",
		"tb":"",
		"type":12
	},
	"filter_condition":{
		"name":"filter_condition",
		"remark":"filter_condition",
		"tb":"",
		"type":12
	},
	"index_name":{
		"name":"index_name",
		"remark":"index_name",
		"tb":"pg_class",
		"type":12
	},
	"index_qualifier":{
		"name":"index_qualifier",
		"remark":"index_qualifier",
		"tb":"",
		"type":12
	},
	"non_unique":{
		"name":"non_unique",
		"remark":"non_unique",
		"tb":"",
		"type":-7
	},
	"ordinal_position":{
		"name":"ordinal_position",
		"remark":"ordinal_position",
		"tb":"",
		"type":4
	},
	"pages":{
		"name":"pages",
		"remark":"pages",
		"tb":"pg_class",
		"type":4
	},
	"table_cat":{
		"name":"table_cat",
		"remark":"table_cat",
		"tb":"",
		"type":12
	},
	"table_name":{
		"name":"table_name",
		"remark":"table_name",
		"tb":"pg_class",
		"type":12
	},
	"table_schem":{
		"name":"table_schem",
		"remark":"table_schem",
		"tb":"pg_namespace",
		"type":12
	},
	"type":{
		"name":"type",
		"remark":"type",
		"tb":"",
		"type":4
	}
}
2018-06-12 22:22:34 [ INFO]-main - Log -Log.java(30)  -{
	"asc_or_desc":{
		"name":"asc_or_desc",
		"remark":"asc_or_desc",
		"tb":"",
		"type":12
	},
	"cardinality":{
		"name":"cardinality",
		"remark":"cardinality",
		"tb":"pg_class",
		"type":7
	},
	"column_name":{
		"name":"column_name",
		"remark":"column_name",
		"tb":"",
		"type":12
	},
	"filter_condition":{
		"name":"filter_condition",
		"remark":"filter_condition",
		"tb":"",
		"type":12
	},
	"index_name":{
		"name":"index_name",
		"remark":"index_name",
		"tb":"pg_class",
		"type":12
	},
	"index_qualifier":{
		"name":"index_qualifier",
		"remark":"index_qualifier",
		"tb":"",
		"type":12
	},
	"non_unique":{
		"name":"non_unique",
		"remark":"non_unique",
		"tb":"",
		"type":-7
	},
	"ordinal_position":{
		"name":"ordinal_position",
		"remark":"ordinal_position",
		"tb":"",
		"type":4
	},
	"pages":{
		"name":"pages",
		"remark":"pages",
		"tb":"pg_class",
		"type":4
	},
	"table_cat":{
		"name":"table_cat",
		"remark":"table_cat",
		"tb":"",
		"type":12
	},
	"table_name":{
		"name":"table_name",
		"remark":"table_name",
		"tb":"pg_class",
		"type":12
	},
	"table_schem":{
		"name":"table_schem",
		"remark":"table_schem",
		"tb":"pg_namespace",
		"type":12
	},
	"type":{
		"name":"type",
		"remark":"type",
		"tb":"",
		"type":4
	}
}
2018-06-12 22:26:53 [ERROR]-main - Log -Log.java(41)  -com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:39)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:27)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:513)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.SQLError.createCommunicationsException(SQLError.java:990)
	at com.mysql.jdbc.MysqlIO.<init>(MysqlIO.java:341)
	at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2186)
	at com.mysql.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:2219)
	at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2014)
	at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:776)
	at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:47)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:39)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:27)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:513)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:386)
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:330)
	at java.sql.DriverManager.getConnection(DriverManager.java:582)
	at java.sql.DriverManager.getConnection(DriverManager.java:185)
	at org.docshare.orm.mysql.MySQLDBHelper.conn(MySQLDBHelper.java:34)
	at org.docshare.orm.mysql.MySQLDBHelper.main(MySQLDBHelper.java:47)
Caused by: java.net.ConnectException: Connection refused: connect
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.PlainSocketImpl.doConnect(PlainSocketImpl.java:333)
	at java.net.PlainSocketImpl.connectToAddress(PlainSocketImpl.java:195)
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:182)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:366)
	at java.net.Socket.connect(Socket.java:519)
	at com.mysql.jdbc.StandardSocketFactory.connect(StandardSocketFactory.java:211)
	at com.mysql.jdbc.MysqlIO.<init>(MysqlIO.java:300)
	... 16 more

2018-06-12 22:26:53 [ERROR]-main - Log -Log.java(41)  -Config [dbhost=localhost, dbname=621m, dbusr=root, dbpwd=123456, port = 3306, tpl_base=null, ctr_base=null,reloadable=true,useSSL=false,interceptors={}]
2018-06-12 22:26:55 [ERROR]-main - Log -Log.java(41)  -com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:39)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:27)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:513)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.SQLError.createCommunicationsException(SQLError.java:990)
	at com.mysql.jdbc.MysqlIO.<init>(MysqlIO.java:341)
	at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2186)
	at com.mysql.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:2219)
	at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2014)
	at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:776)
	at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:47)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:39)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:27)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:513)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:386)
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:330)
	at java.sql.DriverManager.getConnection(DriverManager.java:582)
	at java.sql.DriverManager.getConnection(DriverManager.java:185)
	at org.docshare.orm.mysql.MySQLDBHelper.conn(MySQLDBHelper.java:34)
	at org.docshare.orm.DBHelper.keyColumn(DBHelper.java:327)
	at org.docshare.orm.mysql.MySQLDBHelper.main(MySQLDBHelper.java:49)
Caused by: java.net.ConnectException: Connection refused: connect
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.PlainSocketImpl.doConnect(PlainSocketImpl.java:333)
	at java.net.PlainSocketImpl.connectToAddress(PlainSocketImpl.java:195)
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:182)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:366)
	at java.net.Socket.connect(Socket.java:519)
	at com.mysql.jdbc.StandardSocketFactory.connect(StandardSocketFactory.java:211)
	at com.mysql.jdbc.MysqlIO.<init>(MysqlIO.java:300)
	... 17 more

2018-06-12 22:26:55 [ERROR]-main - Log -Log.java(41)  -Config [dbhost=localhost, dbname=621m, dbusr=root, dbpwd=123456, port = 3306, tpl_base=null, ctr_base=null,reloadable=true,useSSL=false,interceptors={}]
2018-06-12 22:27:02 [ERROR]-main - Log -Log.java(41)  -com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Unknown database '621m'
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:39)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:27)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:513)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.Util.getInstance(Util.java:408)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:944)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3973)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3909)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:873)
	at com.mysql.jdbc.MysqlIO.proceedHandshakeWithPluggableAuthentication(MysqlIO.java:1710)
	at com.mysql.jdbc.MysqlIO.doHandshake(MysqlIO.java:1226)
	at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2188)
	at com.mysql.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:2219)
	at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2014)
	at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:776)
	at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:47)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:39)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:27)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:513)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:386)
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:330)
	at java.sql.DriverManager.getConnection(DriverManager.java:582)
	at java.sql.DriverManager.getConnection(DriverManager.java:185)
	at org.docshare.orm.mysql.MySQLDBHelper.conn(MySQLDBHelper.java:34)
	at org.docshare.orm.mysql.MySQLDBHelper.main(MySQLDBHelper.java:47)

2018-06-12 22:27:02 [ERROR]-main - Log -Log.java(41)  -Config [dbhost=localhost, dbname=621m, dbusr=root, dbpwd=123456, port = 3308, tpl_base=null, ctr_base=null,reloadable=true,useSSL=false,interceptors={}]
2018-06-12 22:27:02 [ERROR]-main - Log -Log.java(41)  -com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Unknown database '621m'
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:39)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:27)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:513)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.Util.getInstance(Util.java:408)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:944)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3973)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3909)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:873)
	at com.mysql.jdbc.MysqlIO.proceedHandshakeWithPluggableAuthentication(MysqlIO.java:1710)
	at com.mysql.jdbc.MysqlIO.doHandshake(MysqlIO.java:1226)
	at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2188)
	at com.mysql.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:2219)
	at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2014)
	at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:776)
	at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:47)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:39)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:27)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:513)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:386)
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:330)
	at java.sql.DriverManager.getConnection(DriverManager.java:582)
	at java.sql.DriverManager.getConnection(DriverManager.java:185)
	at org.docshare.orm.mysql.MySQLDBHelper.conn(MySQLDBHelper.java:34)
	at org.docshare.orm.DBHelper.keyColumn(DBHelper.java:327)
	at org.docshare.orm.mysql.MySQLDBHelper.main(MySQLDBHelper.java:49)

2018-06-12 22:27:02 [ERROR]-main - Log -Log.java(41)  -Config [dbhost=localhost, dbname=621m, dbusr=root, dbpwd=123456, port = 3308, tpl_base=null, ctr_base=null,reloadable=true,useSSL=false,interceptors={}]
2018-06-12 23:37:54 [ INFO]-main - Log -Log.java(30)  -[{"catalog_id":1,"id":1,"name":"af                  "}]
2018-06-12 23:39:20 [ INFO]-main - Log -Log.java(30)  -[{"catalog_id":1,"id":1,"name":"af"}]
2018-06-13 14:29:17 [ERROR]-main - Log -Log.java(41)  -org.postgresql.util.PSQLException: Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:245)
	at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:49)
	at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:195)
	at org.postgresql.Driver.makeConnection(Driver.java:452)
	at org.postgresql.Driver.connect(Driver.java:254)
	at java.sql.DriverManager.getConnection(DriverManager.java:582)
	at java.sql.DriverManager.getConnection(DriverManager.java:185)
	at org.docshare.orm.postgres.PostgresDBHelper.conn(PostgresDBHelper.java:38)
	at org.docshare.orm.DBHelper.listColumn(DBHelper.java:315)
	at org.docshare.orm.postgres.PostgresDelegate.listColumn(PostgresDelegate.java:293)
	at org.docshare.orm.DBTool.<init>(DBTool.java:44)
	at org.docshare.orm.DBTool.getIns(DBTool.java:308)
	at org.docshare.orm.Model.tool(Model.java:37)
	at org.docshare.test.TestPGSQL.testSelect(TestPGSQL.java:23)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at junit.framework.TestCase.runTest(TestCase.java:168)
	at junit.framework.TestCase.runBare(TestCase.java:134)
	at junit.framework.TestResult$1.protect(TestResult.java:110)
	at junit.framework.TestResult.runProtected(TestResult.java:128)
	at junit.framework.TestResult.run(TestResult.java:113)
	at junit.framework.TestCase.run(TestCase.java:124)
	at junit.framework.TestSuite.runTest(TestSuite.java:243)
	at junit.framework.TestSuite.run(TestSuite.java:238)
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:83)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)
Caused by: java.net.ConnectException: Connection refused: connect
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.PlainSocketImpl.doConnect(PlainSocketImpl.java:333)
	at java.net.PlainSocketImpl.connectToAddress(PlainSocketImpl.java:195)
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:182)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:366)
	at java.net.Socket.connect(Socket.java:519)
	at org.postgresql.core.PGStream.<init>(PGStream.java:69)
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:156)
	... 32 more

2018-06-13 14:29:17 [ERROR]-main - Log -Log.java(41)  -Config [dbhost=localhost, dbname=postgres, dbusr=bbb, dbpwd=123456, port = 5432, tpl_base=null, ctr_base=null,reloadable=true,useSSL=false,interceptors={}]
2018-06-13 14:30:43 [ INFO]-main - Log -Log.java(30)  -[{"catalog_id":1,"id":1,"name":"af"}]
2018-06-13 14:32:06 [ INFO]-main - Log -Log.java(30)  -[{"catalog_id":1,"id":1,"name":"af"}]
2018-06-13 14:34:00 [ INFO]-main - Log -Log.java(30)  -[{"catalog_id":1,"id":1,"name":"af"}]
2018-06-13 14:51:07 [ INFO]-main - Log -Log.java(30)  -[{"catalog_id":1,"id":1,"name":"af"}]
2018-06-13 14:51:07 [ INFO]-main - Log -Log.java(30)  -book_pkey
2018-06-13 14:51:07 [ INFO]-main - Log -Log.java(30)  -catalog_pkey
2018-06-13 14:51:07 [ INFO]-main - Log -Log.java(30)  -fki_sfdg
2018-06-13 14:51:07 [ INFO]-main - Log -Log.java(30)  -pg_aggregate_fnoid_index
2018-06-13 14:51:07 [ INFO]-main - Log -Log.java(30)  -pg_am_name_index
2018-06-13 14:51:07 [ INFO]-main - Log -Log.java(30)  -pg_am_oid_index
2018-06-13 14:51:07 [ INFO]-main - Log -Log.java(30)  -pg_amop_fam_strat_index
2018-06-13 14:51:07 [ INFO]-main - Log -Log.java(30)  -pg_amop_oid_index
2018-06-13 14:51:07 [ INFO]-main - Log -Log.java(30)  -pg_amop_opr_fam_index
2018-06-13 14:51:07 [ INFO]-main - Log -Log.java(30)  -pg_amproc_fam_proc_index
2018-06-13 14:51:07 [ INFO]-main - Log -Log.java(30)  -pg_amproc_oid_index
2018-06-13 14:51:07 [ INFO]-main - Log -Log.java(30)  -pg_attrdef_adrelid_adnum_index
2018-06-13 14:51:07 [ INFO]-main - Log -Log.java(30)  -pg_attrdef_oid_index
2018-06-13 14:51:07 [ INFO]-main - Log -Log.java(30)  -pg_attribute_relid_attnam_index
2018-06-13 14:51:07 [ INFO]-main - Log -Log.java(30)  -pg_attribute_relid_attnum_index
2018-06-13 14:51:07 [ INFO]-main - Log -Log.java(30)  -pg_auth_members_member_role_index
2018-06-13 14:51:07 [ INFO]-main - Log -Log.java(30)  -pg_auth_members_role_member_index
2018-06-13 14:51:07 [ INFO]-main - Log -Log.java(30)  -pg_authid_oid_index
2018-06-13 14:51:07 [ INFO]-main - Log -Log.java(30)  -pg_authid_rolname_index
2018-06-13 14:51:07 [ INFO]-main - Log -Log.java(30)  -pg_cast_oid_index
2018-06-13 14:51:07 [ INFO]-main - Log -Log.java(30)  -pg_cast_source_target_index
2018-06-13 14:51:07 [ INFO]-main - Log -Log.java(30)  -pg_class_oid_index
2018-06-13 14:51:07 [ INFO]-main - Log -Log.java(30)  -pg_class_relname_nsp_index
2018-06-13 14:51:07 [ INFO]-main - Log -Log.java(30)  -pg_class_tblspc_relfilenode_index
2018-06-13 14:51:07 [ INFO]-main - Log -Log.java(30)  -pg_collation_name_enc_nsp_index
2018-06-13 14:51:07 [ INFO]-main - Log -Log.java(30)  -pg_collation_oid_index
2018-06-13 14:51:07 [ INFO]-main - Log -Log.java(30)  -pg_constraint_conname_nsp_index
2018-06-13 14:51:07 [ INFO]-main - Log -Log.java(30)  -pg_constraint_conrelid_index
2018-06-13 14:51:07 [ INFO]-main - Log -Log.java(30)  -pg_constraint_contypid_index
2018-06-13 14:51:07 [ INFO]-main - Log -Log.java(30)  -pg_constraint_oid_index
2018-06-13 14:51:07 [ INFO]-main - Log -Log.java(30)  -pg_conversion_default_index
2018-06-13 14:51:07 [ INFO]-main - Log -Log.java(30)  -pg_conversion_name_nsp_index
2018-06-13 14:51:07 [ INFO]-main - Log -Log.java(30)  -pg_conversion_oid_index
2018-06-13 14:51:07 [ INFO]-main - Log -Log.java(30)  -pg_database_datname_index
2018-06-13 14:51:07 [ INFO]-main - Log -Log.java(30)  -pg_database_oid_index
2018-06-13 14:51:07 [ INFO]-main - Log -Log.java(30)  -pg_db_role_setting_databaseid_rol_index
2018-06-13 14:51:07 [ INFO]-main - Log -Log.java(30)  -pg_default_acl_oid_index
2018-06-13 14:51:07 [ INFO]-main - Log -Log.java(30)  -pg_default_acl_role_nsp_obj_index
2018-06-13 14:51:07 [ INFO]-main - Log -Log.java(30)  -pg_depend_depender_index
2018-06-13 14:51:07 [ INFO]-main - Log -Log.java(30)  -pg_depend_reference_index
2018-06-13 14:51:07 [ INFO]-main - Log -Log.java(30)  -pg_description_o_c_o_index
2018-06-13 14:51:07 [ INFO]-main - Log -Log.java(30)  -pg_enum_oid_index
2018-06-13 14:51:07 [ INFO]-main - Log -Log.java(30)  -pg_enum_typid_label_index
2018-06-13 14:51:07 [ INFO]-main - Log -Log.java(30)  -pg_enum_typid_sortorder_index
2018-06-13 14:51:07 [ INFO]-main - Log -Log.java(30)  -pg_event_trigger_evtname_index
2018-06-13 14:51:07 [ INFO]-main - Log -Log.java(30)  -pg_event_trigger_oid_index
2018-06-13 14:51:07 [ INFO]-main - Log -Log.java(30)  -pg_extension_name_index
2018-06-13 14:51:07 [ INFO]-main - Log -Log.java(30)  -pg_extension_oid_index
2018-06-13 14:51:07 [ INFO]-main - Log -Log.java(30)  -pg_foreign_data_wrapper_name_index
2018-06-13 14:51:07 [ INFO]-main - Log -Log.java(30)  -pg_foreign_data_wrapper_oid_index
2018-06-13 14:51:07 [ INFO]-main - Log -Log.java(30)  -pg_foreign_server_name_index
2018-06-13 14:51:07 [ INFO]-main - Log -Log.java(30)  -pg_foreign_server_oid_index
2018-06-13 14:51:07 [ INFO]-main - Log -Log.java(30)  -pg_foreign_table_relid_index
2018-06-13 14:51:07 [ INFO]-main - Log -Log.java(30)  -pg_index_indexrelid_index
2018-06-13 14:51:07 [ INFO]-main - Log -Log.java(30)  -pg_index_indrelid_index
2018-06-13 14:51:07 [ INFO]-main - Log -Log.java(30)  -pg_inherits_parent_index
2018-06-13 14:51:07 [ INFO]-main - Log -Log.java(30)  -pg_inherits_relid_seqno_index
2018-06-13 14:51:07 [ INFO]-main - Log -Log.java(30)  -pg_init_privs_o_c_o_index
2018-06-13 14:51:07 [ INFO]-main - Log -Log.java(30)  -pg_language_name_index
2018-06-13 14:51:07 [ INFO]-main - Log -Log.java(30)  -pg_language_oid_index
2018-06-13 14:51:07 [ INFO]-main - Log -Log.java(30)  -pg_largeobject_loid_pn_index
2018-06-13 14:51:07 [ INFO]-main - Log -Log.java(30)  -pg_largeobject_metadata_oid_index
2018-06-13 14:51:07 [ INFO]-main - Log -Log.java(30)  -pg_namespace_nspname_index
2018-06-13 14:51:07 [ INFO]-main - Log -Log.java(30)  -pg_namespace_oid_index
2018-06-13 14:51:07 [ INFO]-main - Log -Log.java(30)  -pg_opclass_am_name_nsp_index
2018-06-13 14:51:07 [ INFO]-main - Log -Log.java(30)  -pg_opclass_oid_index
2018-06-13 14:51:07 [ INFO]-main - Log -Log.java(30)  -pg_operator_oid_index
2018-06-13 14:51:07 [ INFO]-main - Log -Log.java(30)  -pg_operator_oprname_l_r_n_index
2018-06-13 14:51:07 [ INFO]-main - Log -Log.java(30)  -pg_opfamily_am_name_nsp_index
2018-06-13 14:51:07 [ INFO]-main - Log -Log.java(30)  -pg_opfamily_oid_index
2018-06-13 14:51:07 [ INFO]-main - Log -Log.java(30)  -pg_partitioned_table_partrelid_index
2018-06-13 14:51:07 [ INFO]-main - Log -Log.java(30)  -pg_pltemplate_name_index
2018-06-13 14:51:07 [ INFO]-main - Log -Log.java(30)  -pg_policy_oid_index
2018-06-13 14:51:07 [ INFO]-main - Log -Log.java(30)  -pg_policy_polrelid_polname_index
2018-06-13 14:51:07 [ INFO]-main - Log -Log.java(30)  -pg_proc_oid_index
2018-06-13 14:51:07 [ INFO]-main - Log -Log.java(30)  -pg_proc_proname_args_nsp_index
2018-06-13 14:51:07 [ INFO]-main - Log -Log.java(30)  -pg_publication_oid_index
2018-06-13 14:51:07 [ INFO]-main - Log -Log.java(30)  -pg_publication_pubname_index
2018-06-13 14:51:07 [ INFO]-main - Log -Log.java(30)  -pg_publication_rel_oid_index
2018-06-13 14:51:07 [ INFO]-main - Log -Log.java(30)  -pg_publication_rel_prrelid_prpubid_index
2018-06-13 14:51:07 [ INFO]-main - Log -Log.java(30)  -pg_range_rngtypid_index
2018-06-13 14:51:07 [ INFO]-main - Log -Log.java(30)  -pg_replication_origin_roiident_index
2018-06-13 14:51:07 [ INFO]-main - Log -Log.java(30)  -pg_replication_origin_roname_index
2018-06-13 14:51:07 [ INFO]-main - Log -Log.java(30)  -pg_rewrite_oid_index
2018-06-13 14:51:07 [ INFO]-main - Log -Log.java(30)  -pg_rewrite_rel_rulename_index
2018-06-13 14:51:07 [ INFO]-main - Log -Log.java(30)  -pg_seclabel_object_index
2018-06-13 14:51:07 [ INFO]-main - Log -Log.java(30)  -pg_sequence_seqrelid_index
2018-06-13 14:51:07 [ INFO]-main - Log -Log.java(30)  -pg_shdepend_depender_index
2018-06-13 14:51:07 [ INFO]-main - Log -Log.java(30)  -pg_shdepend_reference_index
2018-06-13 14:51:07 [ INFO]-main - Log -Log.java(30)  -pg_shdescription_o_c_index
2018-06-13 14:51:07 [ INFO]-main - Log -Log.java(30)  -pg_shseclabel_object_index
2018-06-13 14:51:07 [ INFO]-main - Log -Log.java(30)  -pg_statistic_ext_name_index
2018-06-13 14:51:07 [ INFO]-main - Log -Log.java(30)  -pg_statistic_ext_oid_index
2018-06-13 14:51:07 [ INFO]-main - Log -Log.java(30)  -pg_statistic_ext_relid_index
2018-06-13 14:51:07 [ INFO]-main - Log -Log.java(30)  -pg_statistic_relid_att_inh_index
2018-06-13 14:51:07 [ INFO]-main - Log -Log.java(30)  -pg_subscription_oid_index
2018-06-13 14:51:07 [ INFO]-main - Log -Log.java(30)  -pg_subscription_rel_srrelid_srsubid_index
2018-06-13 14:51:07 [ INFO]-main - Log -Log.java(30)  -pg_subscription_subname_index
2018-06-13 14:51:07 [ INFO]-main - Log -Log.java(30)  -pg_tablespace_oid_index
2018-06-13 14:51:07 [ INFO]-main - Log -Log.java(30)  -pg_tablespace_spcname_index
2018-06-13 14:51:07 [ INFO]-main - Log -Log.java(30)  -pg_transform_oid_index
2018-06-13 14:51:07 [ INFO]-main - Log -Log.java(30)  -pg_transform_type_lang_index
2018-06-13 14:51:07 [ INFO]-main - Log -Log.java(30)  -pg_trigger_oid_index
2018-06-13 14:51:07 [ INFO]-main - Log -Log.java(30)  -pg_trigger_tgconstraint_index
2018-06-13 14:51:07 [ INFO]-main - Log -Log.java(30)  -pg_trigger_tgrelid_tgname_index
2018-06-13 14:51:07 [ INFO]-main - Log -Log.java(30)  -pg_ts_config_cfgname_index
2018-06-13 14:51:07 [ INFO]-main - Log -Log.java(30)  -pg_ts_config_map_index
2018-06-13 14:51:07 [ INFO]-main - Log -Log.java(30)  -pg_ts_config_oid_index
2018-06-13 14:51:07 [ INFO]-main - Log -Log.java(30)  -pg_ts_dict_dictname_index
2018-06-13 14:51:07 [ INFO]-main - Log -Log.java(30)  -pg_ts_dict_oid_index
2018-06-13 14:51:07 [ INFO]-main - Log -Log.java(30)  -pg_ts_parser_oid_index
2018-06-13 14:51:07 [ INFO]-main - Log -Log.java(30)  -pg_ts_parser_prsname_index
2018-06-13 14:51:07 [ INFO]-main - Log -Log.java(30)  -pg_ts_template_oid_index
2018-06-13 14:51:07 [ INFO]-main - Log -Log.java(30)  -pg_ts_template_tmplname_index
2018-06-13 14:51:07 [ INFO]-main - Log -Log.java(30)  -pg_type_oid_index
2018-06-13 14:51:07 [ INFO]-main - Log -Log.java(30)  -pg_type_typname_nsp_index
2018-06-13 14:51:07 [ INFO]-main - Log -Log.java(30)  -pg_user_mapping_oid_index
2018-06-13 14:51:07 [ INFO]-main - Log -Log.java(30)  -pg_user_mapping_user_server_index
2018-06-13 14:51:07 [ INFO]-main - Log -Log.java(30)  -sql_features
2018-06-13 14:51:07 [ INFO]-main - Log -Log.java(30)  -sql_implementation_info
2018-06-13 14:51:07 [ INFO]-main - Log -Log.java(30)  -sql_languages
2018-06-13 14:51:07 [ INFO]-main - Log -Log.java(30)  -sql_packages
2018-06-13 14:51:07 [ INFO]-main - Log -Log.java(30)  -sql_parts
2018-06-13 14:51:07 [ INFO]-main - Log -Log.java(30)  -sql_sizing
2018-06-13 14:51:07 [ INFO]-main - Log -Log.java(30)  -sql_sizing_profiles
2018-06-13 14:51:07 [ INFO]-main - Log -Log.java(30)  -pg_aggregate
2018-06-13 14:51:07 [ INFO]-main - Log -Log.java(30)  -pg_am
2018-06-13 14:51:07 [ INFO]-main - Log -Log.java(30)  -pg_amop
2018-06-13 14:51:07 [ INFO]-main - Log -Log.java(30)  -pg_amproc
2018-06-13 14:51:07 [ INFO]-main - Log -Log.java(30)  -pg_attrdef
2018-06-13 14:51:07 [ INFO]-main - Log -Log.java(30)  -pg_attribute
2018-06-13 14:51:07 [ INFO]-main - Log -Log.java(30)  -pg_auth_members
2018-06-13 14:51:07 [ INFO]-main - Log -Log.java(30)  -pg_authid
2018-06-13 14:51:07 [ INFO]-main - Log -Log.java(30)  -pg_cast
2018-06-13 14:51:07 [ INFO]-main - Log -Log.java(30)  -pg_class
2018-06-13 14:51:07 [ INFO]-main - Log -Log.java(30)  -pg_collation
2018-06-13 14:51:07 [ INFO]-main - Log -Log.java(30)  -pg_constraint
2018-06-13 14:51:07 [ INFO]-main - Log -Log.java(30)  -pg_conversion
2018-06-13 14:51:07 [ INFO]-main - Log -Log.java(30)  -pg_database
2018-06-13 14:51:07 [ INFO]-main - Log -Log.java(30)  -pg_db_role_setting
2018-06-13 14:51:07 [ INFO]-main - Log -Log.java(30)  -pg_default_acl
2018-06-13 14:51:07 [ INFO]-main - Log -Log.java(30)  -pg_depend
2018-06-13 14:51:07 [ INFO]-main - Log -Log.java(30)  -pg_description
2018-06-13 14:51:07 [ INFO]-main - Log -Log.java(30)  -pg_enum
2018-06-13 14:51:07 [ INFO]-main - Log -Log.java(30)  -pg_event_trigger
2018-06-13 14:51:07 [ INFO]-main - Log -Log.java(30)  -pg_extension
2018-06-13 14:51:07 [ INFO]-main - Log -Log.java(30)  -pg_foreign_data_wrapper
2018-06-13 14:51:07 [ INFO]-main - Log -Log.java(30)  -pg_foreign_server
2018-06-13 14:51:07 [ INFO]-main - Log -Log.java(30)  -pg_foreign_table
2018-06-13 14:51:07 [ INFO]-main - Log -Log.java(30)  -pg_index
2018-06-13 14:51:07 [ INFO]-main - Log -Log.java(30)  -pg_inherits
2018-06-13 14:51:07 [ INFO]-main - Log -Log.java(30)  -pg_init_privs
2018-06-13 14:51:07 [ INFO]-main - Log -Log.java(30)  -pg_language
2018-06-13 14:51:07 [ INFO]-main - Log -Log.java(30)  -pg_largeobject
2018-06-13 14:51:07 [ INFO]-main - Log -Log.java(30)  -pg_largeobject_metadata
2018-06-13 14:51:07 [ INFO]-main - Log -Log.java(30)  -pg_namespace
2018-06-13 14:51:07 [ INFO]-main - Log -Log.java(30)  -pg_opclass
2018-06-13 14:51:07 [ INFO]-main - Log -Log.java(30)  -pg_operator
2018-06-13 14:51:07 [ INFO]-main - Log -Log.java(30)  -pg_opfamily
2018-06-13 14:51:07 [ INFO]-main - Log -Log.java(30)  -pg_partitioned_table
2018-06-13 14:51:07 [ INFO]-main - Log -Log.java(30)  -pg_pltemplate
2018-06-13 14:51:07 [ INFO]-main - Log -Log.java(30)  -pg_policy
2018-06-13 14:51:07 [ INFO]-main - Log -Log.java(30)  -pg_proc
2018-06-13 14:51:07 [ INFO]-main - Log -Log.java(30)  -pg_publication
2018-06-13 14:51:07 [ INFO]-main - Log -Log.java(30)  -pg_publication_rel
2018-06-13 14:51:07 [ INFO]-main - Log -Log.java(30)  -pg_range
2018-06-13 14:51:07 [ INFO]-main - Log -Log.java(30)  -pg_replication_origin
2018-06-13 14:51:07 [ INFO]-main - Log -Log.java(30)  -pg_rewrite
2018-06-13 14:51:07 [ INFO]-main - Log -Log.java(30)  -pg_seclabel
2018-06-13 14:51:07 [ INFO]-main - Log -Log.java(30)  -pg_sequence
2018-06-13 14:51:07 [ INFO]-main - Log -Log.java(30)  -pg_shdepend
2018-06-13 14:51:07 [ INFO]-main - Log -Log.java(30)  -pg_shdescription
2018-06-13 14:51:07 [ INFO]-main - Log -Log.java(30)  -pg_shseclabel
2018-06-13 14:51:07 [ INFO]-main - Log -Log.java(30)  -pg_statistic
2018-06-13 14:51:07 [ INFO]-main - Log -Log.java(30)  -pg_statistic_ext
2018-06-13 14:51:07 [ INFO]-main - Log -Log.java(30)  -pg_subscription
2018-06-13 14:51:07 [ INFO]-main - Log -Log.java(30)  -pg_subscription_rel
2018-06-13 14:51:07 [ INFO]-main - Log -Log.java(30)  -pg_tablespace
2018-06-13 14:51:07 [ INFO]-main - Log -Log.java(30)  -pg_transform
2018-06-13 14:51:07 [ INFO]-main - Log -Log.java(30)  -pg_trigger
2018-06-13 14:51:07 [ INFO]-main - Log -Log.java(30)  -pg_ts_config
2018-06-13 14:51:07 [ INFO]-main - Log -Log.java(30)  -pg_ts_config_map
2018-06-13 14:51:07 [ INFO]-main - Log -Log.java(30)  -pg_ts_dict
2018-06-13 14:51:07 [ INFO]-main - Log -Log.java(30)  -pg_ts_parser
2018-06-13 14:51:07 [ INFO]-main - Log -Log.java(30)  -pg_ts_template
2018-06-13 14:51:07 [ INFO]-main - Log -Log.java(30)  -pg_type
2018-06-13 14:51:07 [ INFO]-main - Log -Log.java(30)  -pg_user_mapping
2018-06-13 14:51:07 [ INFO]-main - Log -Log.java(30)  -pg_toast_1255_index
2018-06-13 14:51:07 [ INFO]-main - Log -Log.java(30)  -pg_toast_12773_index
2018-06-13 14:51:07 [ INFO]-main - Log -Log.java(30)  -pg_toast_12778_index
2018-06-13 14:51:07 [ INFO]-main - Log -Log.java(30)  -pg_toast_12783_index
2018-06-13 14:51:07 [ INFO]-main - Log -Log.java(30)  -pg_toast_12788_index
2018-06-13 14:51:07 [ INFO]-main - Log -Log.java(30)  -pg_toast_12793_index
2018-06-13 14:51:07 [ INFO]-main - Log -Log.java(30)  -pg_toast_12798_index
2018-06-13 14:51:07 [ INFO]-main - Log -Log.java(30)  -pg_toast_12803_index
2018-06-13 14:51:07 [ INFO]-main - Log -Log.java(30)  -pg_toast_2396_index
2018-06-13 14:51:07 [ INFO]-main - Log -Log.java(30)  -pg_toast_2604_index
2018-06-13 14:51:07 [ INFO]-main - Log -Log.java(30)  -pg_toast_2606_index
2018-06-13 14:51:07 [ INFO]-main - Log -Log.java(30)  -pg_toast_2609_index
2018-06-13 14:51:07 [ INFO]-main - Log -Log.java(30)  -pg_toast_2618_index
2018-06-13 14:51:07 [ INFO]-main - Log -Log.java(30)  -pg_toast_2619_index
2018-06-13 14:51:07 [ INFO]-main - Log -Log.java(30)  -pg_toast_2620_index
2018-06-13 14:51:07 [ INFO]-main - Log -Log.java(30)  -pg_toast_2964_index
2018-06-13 14:51:07 [ INFO]-main - Log -Log.java(30)  -pg_toast_3381_index
2018-06-13 14:51:07 [ INFO]-main - Log -Log.java(30)  -pg_toast_3592_index
2018-06-13 14:51:07 [ INFO]-main - Log -Log.java(30)  -pg_toast_3596_index
2018-06-13 14:51:07 [ INFO]-main - Log -Log.java(30)  -_pg_foreign_data_wrappers
2018-06-13 14:51:07 [ INFO]-main - Log -Log.java(30)  -_pg_foreign_servers
2018-06-13 14:51:07 [ INFO]-main - Log -Log.java(30)  -_pg_foreign_table_columns
2018-06-13 14:51:07 [ INFO]-main - Log -Log.java(30)  -_pg_foreign_tables
2018-06-13 14:51:07 [ INFO]-main - Log -Log.java(30)  -_pg_user_mappings
2018-06-13 14:51:07 [ INFO]-main - Log -Log.java(30)  -administrable_role_authorizations
2018-06-13 14:51:07 [ INFO]-main - Log -Log.java(30)  -applicable_roles
2018-06-13 14:51:07 [ INFO]-main - Log -Log.java(30)  -attributes
2018-06-13 14:51:07 [ INFO]-main - Log -Log.java(30)  -character_sets
2018-06-13 14:51:07 [ INFO]-main - Log -Log.java(30)  -check_constraint_routine_usage
2018-06-13 14:51:07 [ INFO]-main - Log -Log.java(30)  -check_constraints
2018-06-13 14:51:07 [ INFO]-main - Log -Log.java(30)  -collation_character_set_applicability
2018-06-13 14:51:07 [ INFO]-main - Log -Log.java(30)  -collations
2018-06-13 14:51:07 [ INFO]-main - Log -Log.java(30)  -column_domain_usage
2018-06-13 14:51:07 [ INFO]-main - Log -Log.java(30)  -column_options
2018-06-13 14:51:07 [ INFO]-main - Log -Log.java(30)  -column_privileges
2018-06-13 14:51:07 [ INFO]-main - Log -Log.java(30)  -column_udt_usage
2018-06-13 14:51:07 [ INFO]-main - Log -Log.java(30)  -columns
2018-06-13 14:51:07 [ INFO]-main - Log -Log.java(30)  -constraint_column_usage
2018-06-13 14:51:07 [ INFO]-main - Log -Log.java(30)  -constraint_table_usage
2018-06-13 14:51:07 [ INFO]-main - Log -Log.java(30)  -data_type_privileges
2018-06-13 14:51:07 [ INFO]-main - Log -Log.java(30)  -domain_constraints
2018-06-13 14:51:07 [ INFO]-main - Log -Log.java(30)  -domain_udt_usage
2018-06-13 14:51:07 [ INFO]-main - Log -Log.java(30)  -domains
2018-06-13 14:51:07 [ INFO]-main - Log -Log.java(30)  -element_types
2018-06-13 14:51:07 [ INFO]-main - Log -Log.java(30)  -enabled_roles
2018-06-13 14:51:07 [ INFO]-main - Log -Log.java(30)  -foreign_data_wrapper_options
2018-06-13 14:51:07 [ INFO]-main - Log -Log.java(30)  -foreign_data_wrappers
2018-06-13 14:51:07 [ INFO]-main - Log -Log.java(30)  -foreign_server_options
2018-06-13 14:51:07 [ INFO]-main - Log -Log.java(30)  -foreign_servers
2018-06-13 14:51:07 [ INFO]-main - Log -Log.java(30)  -foreign_table_options
2018-06-13 14:51:07 [ INFO]-main - Log -Log.java(30)  -foreign_tables
2018-06-13 14:51:07 [ INFO]-main - Log -Log.java(30)  -information_schema_catalog_name
2018-06-13 14:51:07 [ INFO]-main - Log -Log.java(30)  -key_column_usage
2018-06-13 14:51:07 [ INFO]-main - Log -Log.java(30)  -parameters
2018-06-13 14:51:07 [ INFO]-main - Log -Log.java(30)  -referential_constraints
2018-06-13 14:51:07 [ INFO]-main - Log -Log.java(30)  -role_column_grants
2018-06-13 14:51:07 [ INFO]-main - Log -Log.java(30)  -role_routine_grants
2018-06-13 14:51:07 [ INFO]-main - Log -Log.java(30)  -role_table_grants
2018-06-13 14:51:07 [ INFO]-main - Log -Log.java(30)  -role_udt_grants
2018-06-13 14:51:07 [ INFO]-main - Log -Log.java(30)  -role_usage_grants
2018-06-13 14:51:07 [ INFO]-main - Log -Log.java(30)  -routine_privileges
2018-06-13 14:51:07 [ INFO]-main - Log -Log.java(30)  -routines
2018-06-13 14:51:07 [ INFO]-main - Log -Log.java(30)  -schemata
2018-06-13 14:51:07 [ INFO]-main - Log -Log.java(30)  -sequences
2018-06-13 14:51:07 [ INFO]-main - Log -Log.java(30)  -table_constraints
2018-06-13 14:51:07 [ INFO]-main - Log -Log.java(30)  -table_privileges
2018-06-13 14:51:07 [ INFO]-main - Log -Log.java(30)  -tables
2018-06-13 14:51:07 [ INFO]-main - Log -Log.java(30)  -transforms
2018-06-13 14:51:07 [ INFO]-main - Log -Log.java(30)  -triggered_update_columns
2018-06-13 14:51:07 [ INFO]-main - Log -Log.java(30)  -triggers
2018-06-13 14:51:07 [ INFO]-main - Log -Log.java(30)  -udt_privileges
2018-06-13 14:51:07 [ INFO]-main - Log -Log.java(30)  -usage_privileges
2018-06-13 14:51:07 [ INFO]-main - Log -Log.java(30)  -user_defined_types
2018-06-13 14:51:07 [ INFO]-main - Log -Log.java(30)  -user_mapping_options
2018-06-13 14:51:07 [ INFO]-main - Log -Log.java(30)  -user_mappings
2018-06-13 14:51:07 [ INFO]-main - Log -Log.java(30)  -view_column_usage
2018-06-13 14:51:07 [ INFO]-main - Log -Log.java(30)  -view_routine_usage
2018-06-13 14:51:07 [ INFO]-main - Log -Log.java(30)  -view_table_usage
2018-06-13 14:51:07 [ INFO]-main - Log -Log.java(30)  -views
2018-06-13 14:51:07 [ INFO]-main - Log -Log.java(30)  -pg_available_extension_versions
2018-06-13 14:51:07 [ INFO]-main - Log -Log.java(30)  -pg_available_extensions
2018-06-13 14:51:07 [ INFO]-main - Log -Log.java(30)  -pg_config
2018-06-13 14:51:07 [ INFO]-main - Log -Log.java(30)  -pg_cursors
2018-06-13 14:51:07 [ INFO]-main - Log -Log.java(30)  -pg_file_settings
2018-06-13 14:51:07 [ INFO]-main - Log -Log.java(30)  -pg_group
2018-06-13 14:51:07 [ INFO]-main - Log -Log.java(30)  -pg_hba_file_rules
2018-06-13 14:51:07 [ INFO]-main - Log -Log.java(30)  -pg_indexes
2018-06-13 14:51:07 [ INFO]-main - Log -Log.java(30)  -pg_locks
2018-06-13 14:51:07 [ INFO]-main - Log -Log.java(30)  -pg_matviews
2018-06-13 14:51:07 [ INFO]-main - Log -Log.java(30)  -pg_policies
2018-06-13 14:51:07 [ INFO]-main - Log -Log.java(30)  -pg_prepared_statements
2018-06-13 14:51:07 [ INFO]-main - Log -Log.java(30)  -pg_prepared_xacts
2018-06-13 14:51:07 [ INFO]-main - Log -Log.java(30)  -pg_publication_tables
2018-06-13 14:51:07 [ INFO]-main - Log -Log.java(30)  -pg_replication_origin_status
2018-06-13 14:51:07 [ INFO]-main - Log -Log.java(30)  -pg_replication_slots
2018-06-13 14:51:07 [ INFO]-main - Log -Log.java(30)  -pg_roles
2018-06-13 14:51:07 [ INFO]-main - Log -Log.java(30)  -pg_rules
2018-06-13 14:51:07 [ INFO]-main - Log -Log.java(30)  -pg_seclabels
2018-06-13 14:51:07 [ INFO]-main - Log -Log.java(30)  -pg_sequences
2018-06-13 14:51:07 [ INFO]-main - Log -Log.java(30)  -pg_settings
2018-06-13 14:51:07 [ INFO]-main - Log -Log.java(30)  -pg_shadow
2018-06-13 14:51:07 [ INFO]-main - Log -Log.java(30)  -pg_stat_activity
2018-06-13 14:51:07 [ INFO]-main - Log -Log.java(30)  -pg_stat_all_indexes
2018-06-13 14:51:07 [ INFO]-main - Log -Log.java(30)  -pg_stat_all_tables
2018-06-13 14:51:07 [ INFO]-main - Log -Log.java(30)  -pg_stat_archiver
2018-06-13 14:51:07 [ INFO]-main - Log -Log.java(30)  -pg_stat_bgwriter
2018-06-13 14:51:07 [ INFO]-main - Log -Log.java(30)  -pg_stat_database
2018-06-13 14:51:07 [ INFO]-main - Log -Log.java(30)  -pg_stat_database_conflicts
2018-06-13 14:51:07 [ INFO]-main - Log -Log.java(30)  -pg_stat_progress_vacuum
2018-06-13 14:51:07 [ INFO]-main - Log -Log.java(30)  -pg_stat_replication
2018-06-13 14:51:07 [ INFO]-main - Log -Log.java(30)  -pg_stat_ssl
2018-06-13 14:51:07 [ INFO]-main - Log -Log.java(30)  -pg_stat_subscription
2018-06-13 14:51:07 [ INFO]-main - Log -Log.java(30)  -pg_stat_sys_indexes
2018-06-13 14:51:07 [ INFO]-main - Log -Log.java(30)  -pg_stat_sys_tables
2018-06-13 14:51:07 [ INFO]-main - Log -Log.java(30)  -pg_stat_user_functions
2018-06-13 14:51:07 [ INFO]-main - Log -Log.java(30)  -pg_stat_user_indexes
2018-06-13 14:51:07 [ INFO]-main - Log -Log.java(30)  -pg_stat_user_tables
2018-06-13 14:51:07 [ INFO]-main - Log -Log.java(30)  -pg_stat_wal_receiver
2018-06-13 14:51:07 [ INFO]-main - Log -Log.java(30)  -pg_stat_xact_all_tables
2018-06-13 14:51:07 [ INFO]-main - Log -Log.java(30)  -pg_stat_xact_sys_tables
2018-06-13 14:51:07 [ INFO]-main - Log -Log.java(30)  -pg_stat_xact_user_functions
2018-06-13 14:51:07 [ INFO]-main - Log -Log.java(30)  -pg_stat_xact_user_tables
2018-06-13 14:51:07 [ INFO]-main - Log -Log.java(30)  -pg_statio_all_indexes
2018-06-13 14:51:07 [ INFO]-main - Log -Log.java(30)  -pg_statio_all_sequences
2018-06-13 14:51:07 [ INFO]-main - Log -Log.java(30)  -pg_statio_all_tables
2018-06-13 14:51:07 [ INFO]-main - Log -Log.java(30)  -pg_statio_sys_indexes
2018-06-13 14:51:07 [ INFO]-main - Log -Log.java(30)  -pg_statio_sys_sequences
2018-06-13 14:51:07 [ INFO]-main - Log -Log.java(30)  -pg_statio_sys_tables
2018-06-13 14:51:07 [ INFO]-main - Log -Log.java(30)  -pg_statio_user_indexes
2018-06-13 14:51:07 [ INFO]-main - Log -Log.java(30)  -pg_statio_user_sequences
2018-06-13 14:51:07 [ INFO]-main - Log -Log.java(30)  -pg_statio_user_tables
2018-06-13 14:51:07 [ INFO]-main - Log -Log.java(30)  -pg_stats
2018-06-13 14:51:07 [ INFO]-main - Log -Log.java(30)  -pg_tables
2018-06-13 14:51:07 [ INFO]-main - Log -Log.java(30)  -pg_timezone_abbrevs
2018-06-13 14:51:07 [ INFO]-main - Log -Log.java(30)  -pg_timezone_names
2018-06-13 14:51:07 [ INFO]-main - Log -Log.java(30)  -pg_user
2018-06-13 14:51:07 [ INFO]-main - Log -Log.java(30)  -pg_user_mappings
2018-06-13 14:51:07 [ INFO]-main - Log -Log.java(30)  -pg_views
2018-06-13 14:51:07 [ INFO]-main - Log -Log.java(30)  -book
2018-06-13 14:51:07 [ INFO]-main - Log -Log.java(30)  -catalog
2018-06-13 14:51:07 [ INFO]-main - Log -Log.java(30)  -pg_toast_1255
2018-06-13 14:51:07 [ INFO]-main - Log -Log.java(30)  -pg_toast_12773
2018-06-13 14:51:07 [ INFO]-main - Log -Log.java(30)  -pg_toast_12778
2018-06-13 14:51:07 [ INFO]-main - Log -Log.java(30)  -pg_toast_12783
2018-06-13 14:51:07 [ INFO]-main - Log -Log.java(30)  -pg_toast_12788
2018-06-13 14:51:07 [ INFO]-main - Log -Log.java(30)  -pg_toast_12793
2018-06-13 14:51:07 [ INFO]-main - Log -Log.java(30)  -pg_toast_12798
2018-06-13 14:51:07 [ INFO]-main - Log -Log.java(30)  -pg_toast_12803
2018-06-13 14:51:07 [ INFO]-main - Log -Log.java(30)  -pg_toast_2396
2018-06-13 14:51:07 [ INFO]-main - Log -Log.java(30)  -pg_toast_2604
2018-06-13 14:51:07 [ INFO]-main - Log -Log.java(30)  -pg_toast_2606
2018-06-13 14:51:07 [ INFO]-main - Log -Log.java(30)  -pg_toast_2609
2018-06-13 14:51:07 [ INFO]-main - Log -Log.java(30)  -pg_toast_2618
2018-06-13 14:51:07 [ INFO]-main - Log -Log.java(30)  -pg_toast_2619
2018-06-13 14:51:07 [ INFO]-main - Log -Log.java(30)  -pg_toast_2620
2018-06-13 14:51:07 [ INFO]-main - Log -Log.java(30)  -pg_toast_2964
2018-06-13 14:51:07 [ INFO]-main - Log -Log.java(30)  -pg_toast_3381
2018-06-13 14:51:07 [ INFO]-main - Log -Log.java(30)  -pg_toast_3592
2018-06-13 14:51:07 [ INFO]-main - Log -Log.java(30)  -pg_toast_3596
2018-06-13 14:52:55 [ INFO]-main - Log -Log.java(30)  -[{"catalog_id":1,"id":1,"name":"af"}]
2018-06-13 14:52:55 [ INFO]-main - Log -Log.java(30)  -book_pkey
2018-06-13 14:52:55 [ INFO]-main - Log -Log.java(30)  -catalog_pkey
2018-06-13 14:52:55 [ INFO]-main - Log -Log.java(30)  -fki_sfdg
2018-06-13 14:52:55 [ INFO]-main - Log -Log.java(30)  -book
2018-06-13 14:52:55 [ INFO]-main - Log -Log.java(30)  -catalog
2018-06-13 14:55:05 [ INFO]-main - Log -Log.java(30)  -book
2018-06-13 14:55:05 [ INFO]-main - Log -Log.java(30)  -catalog
2018-06-13 14:59:11 [ INFO]-main - Log -Log.java(38)  -{"name":"book","schema":"public","type":"TABLE"}
2018-06-13 14:59:11 [ INFO]-main - Log -Log.java(38)  -{"name":"catalog","schema":"public","type":"TABLE"}
2018-06-13 15:00:48 [ INFO]-main - Log -Log.java(38)  -[{"name":"book","schema":"public","type":"TABLE"},{"name":"catalog","schema":"public","type":"TABLE"}]
2018-06-13 15:01:06 [ INFO]-main - Log -Log.java(38)  -[
	{
		"name":"book",
		"schema":"public",
		"type":"TABLE"
	},
	{
		"name":"catalog",
		"schema":"public",
		"type":"TABLE"
	}
]
2018-06-13 15:02:47 [ INFO]-main - Log -Log.java(38)  -[{"catalog_id":1,"id":1,"name":"af"}]
2018-06-13 15:02:47 [ INFO]-main - Log -Log.java(38)  -[
	{
		"name":"book",
		"schema":"public",
		"type":"TABLE"
	},
	{
		"name":"catalog",
		"schema":"public",
		"type":"TABLE"
	}
]
2018-06-13 15:28:25 [ERROR]-main - Log -Log.java(49)  -Config file NOT found : web.properties 
2018-06-13 15:28:25 [ INFO]-main - Log -Log.java(38)  -web.properties NOT load 
2018-06-13 15:28:59 [ INFO]-main - Log -Log.java(38)  -Config file found ! 
2018-06-13 15:28:59 [ INFO]-main - Log -Log.java(38)  -web.properties loaded 
2018-06-13 15:29:25 [ INFO]-main - Log -Log.java(38)  -Config file found ! 
2018-06-13 15:29:25 [ INFO]-main - Log -Log.java(38)  -web.properties loaded 
2018-06-13 15:29:25 [ INFO]-main - Log -Log.java(38)  -Config [dbhost=localhost, dbname=mvc_demo, dbusr=root, dbpwd=123456, port = 3306, tpl_base=null, ctr_base=null,reloadable=true,useSSL=false,interceptors={}]
2018-06-13 15:30:06 [ INFO]-main - Log -Log.java(38)  -Config file found ! 
2018-06-13 15:30:06 [ INFO]-main - Log -Log.java(38)  -web.properties loaded 
2018-06-13 15:30:06 [ INFO]-main - Log -Log.java(38)  -Config [dbhost=localhost, dbname=mvc_demo, dbusr=root, dbpwd=123456, port = 3306, tpl_base=null, ctr_base=null,reloadable=true,useSSL=false,interceptors={}]
2018-06-13 15:30:15 [ INFO]-main - Log -Log.java(38)  -Config file found ! 
2018-06-13 15:30:15 [ INFO]-main - Log -Log.java(38)  -web.properties loaded 
2018-06-13 15:30:15 [ INFO]-main - Log -Log.java(38)  -Config [dbhost=localhost, dbname=mvc_demo, dbusr=root, dbpwd=123456, port = 3306, tpl_base=null, ctr_base=null,reloadable=true,useSSL=false,interceptors={}]
2018-06-13 15:30:51 [ INFO]-main - Log -Log.java(38)  -Config file found ! 
2018-06-13 15:30:51 [ INFO]-main - Log -Log.java(38)  -web.properties loaded 
2018-06-13 15:30:51 [ INFO]-main - Log -Log.java(38)  -Config [dbhost=localhost, dbname=mvc_demo, dbusr=root, dbpwd=123456, port = 3306, tpl_base=null, ctr_base=null,reloadable=true,useSSL=false,interceptors={}]
2018-06-13 15:31:14 [ INFO]-main - Log -Log.java(38)  -Config file found ! 
2018-06-13 15:31:14 [ INFO]-main - Log -Log.java(38)  -web.properties loaded 
2018-06-13 15:31:14 [ INFO]-main - Log -Log.java(38)  -Config [dbhost=localhost, dbname=mvc_demo, dbusr=root, dbpwd=123456, port = 3306, tpl_base=null, ctr_base=null,reloadable=true,useSSL=false,interceptors={}]
2018-06-13 15:33:34 [ERROR]-main - Log -Log.java(49)  -Config file NOT found : web.properties 
2018-06-13 15:33:34 [ INFO]-main - Log -Log.java(38)  -web.properties NOT load 
2018-06-13 15:34:05 [ERROR]-main - Log -Log.java(49)  -Config file NOT found : web.properties 
2018-06-13 15:34:05 [ INFO]-main - Log -Log.java(38)  -web.properties NOT load 
2018-06-13 15:34:54 [ERROR]-main - Log -Log.java(49)  -Config file NOT found : /last.properties
2018-06-13 15:34:54 [ INFO]-main - Log -Log.java(38)  -/last.properties NOT load 
2018-06-13 15:35:44 [ INFO]-main - Log -Log.java(38)  -Config file found ! 
2018-06-13 15:35:44 [ INFO]-main - Log -Log.java(38)  -/last.properties loaded 
2018-06-13 15:35:44 [ INFO]-main - Log -Log.java(38)  -Config [dbhost=localhost, dbname=postgres, dbusr=bbb, dbpwd=123456, port = 3306, tpl_base=null, ctr_base=null,reloadable=true,useSSL=false,interceptors={}]
2018-06-13 15:36:04 [ INFO]-main - Log -Log.java(38)  -Config file found ! 
2018-06-13 15:36:04 [ INFO]-main - Log -Log.java(38)  -/last.properties loaded 
2018-06-13 15:36:04 [ INFO]-main - Log -Log.java(38)  -Config [dbhost=localhost, dbname=postgres, dbusr=bbb, dbpwd=123456, port = 3306, tpl_base=null, ctr_base=null,reloadable=true,useSSL=false,interceptors={}]
2018-06-13 15:36:20 [ INFO]-main - Log -Log.java(38)  -Config file found ! 
2018-06-13 15:36:20 [ INFO]-main - Log -Log.java(38)  -/last.properties loaded 
2018-06-13 15:36:39 [ INFO]-main - Log -Log.java(38)  -Config file found ! 
2018-06-13 15:36:39 [ INFO]-main - Log -Log.java(38)  -/last.properties loaded 
2018-06-13 15:41:33 [ INFO]-main - Log -Log.java(38)  -Config file found ! 
2018-06-13 15:41:33 [ INFO]-main - Log -Log.java(38)  -/last.properties loaded 
2018-06-13 15:44:25 [ INFO]-main - Log -Log.java(38)  -[{"catalog_id":1,"id":1,"name":"af"}]
2018-06-13 15:44:25 [ INFO]-main - Log -Log.java(38)  -[
	{
		"name":"book",
		"schema":"public",
		"type":"TABLE"
	},
	{
		"name":"catalog",
		"schema":"public",
		"type":"TABLE"
	}
]
2018-06-13 15:44:25 [ INFO]-main - Log -Log.java(38)  -{
	"catalog_id":1,
	"id":1,
	"name":"af"
}
2018-06-13 15:45:02 [ INFO]-main - Log -Log.java(38)  -[{"catalog_id":1,"id":1,"name":"af"}]
2018-06-13 15:45:02 [ INFO]-main - Log -Log.java(38)  -[
	{
		"name":"book",
		"schema":"public",
		"type":"TABLE"
	},
	{
		"name":"catalog",
		"schema":"public",
		"type":"TABLE"
	}
]
2018-06-13 15:45:02 [ INFO]-main - Log -Log.java(38)  -{
	"catalog_id":1,
	"id":1,
	"name":"af"
}
2018-06-13 15:45:02 [ERROR]-main - Log -Log.java(49)  -exec sql fail update "book" set "id"=?,"name"=?,"catalog_id"=? where id='1' ,param = 1,ccWed Jun 13 15:45:02 CST 2018,1
2018-06-13 15:45:02 [ERROR]-main - Log -Log.java(49)  -org.postgresql.util.PSQLException: 错误: 对于可变字符类型来说，值太长了(20)
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2433)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2178)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:306)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:441)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:365)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:155)
	at org.postgresql.jdbc.PgPreparedStatement.executeUpdate(PgPreparedStatement.java:132)
	at org.docshare.orm.DBHelper.updateWithArray(DBHelper.java:241)
	at org.docshare.orm.postgres.PostgresDelegate.save(PostgresDelegate.java:90)
	at org.docshare.orm.DBTool.save(DBTool.java:205)
	at org.docshare.orm.DBTool.save(DBTool.java:183)
	at org.docshare.orm.DBTool.save(DBTool.java:191)
	at org.demo.pojo.Book.update(Book.java:16)
	at org.docshare.test.TestPGSQL.testPOJO(TestPGSQL.java:70)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at junit.framework.TestCase.runTest(TestCase.java:168)
	at junit.framework.TestCase.runBare(TestCase.java:134)
	at junit.framework.TestResult$1.protect(TestResult.java:110)
	at junit.framework.TestResult.runProtected(TestResult.java:128)
	at junit.framework.TestResult.run(TestResult.java:113)
	at junit.framework.TestCase.run(TestCase.java:124)
	at junit.framework.TestSuite.runTest(TestSuite.java:243)
	at junit.framework.TestSuite.run(TestSuite.java:238)
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:83)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)

2018-06-13 15:45:24 [ INFO]-main - Log -Log.java(38)  -[{"catalog_id":1,"id":1,"name":"af"}]
2018-06-13 15:45:24 [ INFO]-main - Log -Log.java(38)  -[
	{
		"name":"book",
		"schema":"public",
		"type":"TABLE"
	},
	{
		"name":"catalog",
		"schema":"public",
		"type":"TABLE"
	}
]
2018-06-13 15:45:24 [ INFO]-main - Log -Log.java(38)  -{
	"catalog_id":1,
	"id":1,
	"name":"af"
}
2018-06-13 15:45:45 [ INFO]-main - Log -Log.java(38)  -[{"catalog_id":1,"id":1,"name":"ccWed Jun 13 15:45:24 CST 2018"}]
2018-06-13 15:45:45 [ INFO]-main - Log -Log.java(38)  -[
	{
		"name":"book",
		"schema":"public",
		"type":"TABLE"
	},
	{
		"name":"catalog",
		"schema":"public",
		"type":"TABLE"
	}
]
2018-06-13 15:45:45 [ INFO]-main - Log -Log.java(38)  -{
	"catalog_id":1,
	"id":1,
	"name":"ccWed Jun 13 15:45:24 CST 2018"
}
2018-06-13 15:45:50 [ INFO]-main - Log -Log.java(38)  -[{"catalog_id":1,"id":1,"name":"测试45"}]
2018-06-13 15:45:50 [ INFO]-main - Log -Log.java(38)  -[
	{
		"name":"book",
		"schema":"public",
		"type":"TABLE"
	},
	{
		"name":"catalog",
		"schema":"public",
		"type":"TABLE"
	}
]
2018-06-13 15:45:50 [ INFO]-main - Log -Log.java(38)  -{
	"catalog_id":1,
	"id":1,
	"name":"测试45"
}
2018-06-13 15:45:53 [ INFO]-main - Log -Log.java(38)  -{
	"catalog_id":1,
	"id":1,
	"name":"测试45"
}
2018-06-13 15:46:04 [ INFO]-main - Log -Log.java(38)  -[{"catalog_id":1,"id":1,"name":"测试45"}]
2018-06-13 15:46:04 [ INFO]-main - Log -Log.java(38)  -[
	{
		"name":"book",
		"schema":"public",
		"type":"TABLE"
	},
	{
		"name":"catalog",
		"schema":"public",
		"type":"TABLE"
	}
]
2018-06-13 15:46:04 [ INFO]-main - Log -Log.java(38)  -{
	"catalog_id":1,
	"id":1,
	"name":"测试45"
}
2018-06-13 15:46:11 [ INFO]-main - Log -Log.java(38)  -{
	"catalog_id":1,
	"id":1,
	"name":"测试4"
}
2018-06-13 15:46:13 [ INFO]-main - Log -Log.java(38)  -{
	"catalog_id":1,
	"id":1,
	"name":"测试11"
}
2018-06-13 15:46:59 [ INFO]-main - Log -Log.java(38)  -[{"catalog_id":1,"id":1,"name":"测试13"}]
2018-06-13 15:46:59 [ INFO]-main - Log -Log.java(38)  -[
	{
		"name":"book",
		"schema":"public",
		"type":"TABLE"
	},
	{
		"name":"catalog",
		"schema":"public",
		"type":"TABLE"
	}
]
2018-06-13 15:46:59 [ INFO]-main - Log -Log.java(38)  -{
	"catalog_id":1,
	"id":1,
	"name":"测试13"
}
2018-06-13 16:00:25 [ INFO]-main - Log -Log.java(38)  -[{"catalog_id":1,"id":1,"name":"测试59"},{"catalog_id":1,"id":2,"name":"haha"}]
2018-06-13 16:00:25 [ INFO]-main - Log -Log.java(38)  -[
	{
		"name":"book",
		"schema":"public",
		"type":"TABLE"
	},
	{
		"name":"catalog",
		"schema":"public",
		"type":"TABLE"
	}
]
2018-06-13 16:00:25 [ INFO]-main - Log -Log.java(38)  -{
	"catalog_id":1,
	"id":1,
	"name":"测试59"
}
2018-06-13 16:00:25 [ERROR]-main - Log -Log.java(49)  -exec sql fail insert into "book"("id","name","catalog_id") values(?,?,?) ,param = 2,haha,1
2018-06-13 16:00:25 [ERROR]-main - Log -Log.java(49)  -org.postgresql.util.PSQLException: 错误: 重复键违反唯一约束"book_pkey"
  详细：键值"(id)=(2)" 已经存在
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2433)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2178)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:306)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:441)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:365)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:155)
	at org.postgresql.jdbc.PgPreparedStatement.executeUpdate(PgPreparedStatement.java:132)
	at org.docshare.orm.DBHelper.updateWithArray(DBHelper.java:241)
	at org.docshare.orm.postgres.PostgresDelegate.save(PostgresDelegate.java:90)
	at org.docshare.orm.DBTool.save(DBTool.java:205)
	at org.docshare.orm.DBTool.save(DBTool.java:183)
	at org.demo.pojo.Book.insert(Book.java:22)
	at org.docshare.test.TestPGSQL.testPOJO(TestPGSQL.java:78)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at junit.framework.TestCase.runTest(TestCase.java:168)
	at junit.framework.TestCase.runBare(TestCase.java:134)
	at junit.framework.TestResult$1.protect(TestResult.java:110)
	at junit.framework.TestResult.runProtected(TestResult.java:128)
	at junit.framework.TestResult.run(TestResult.java:113)
	at junit.framework.TestCase.run(TestCase.java:124)
	at junit.framework.TestSuite.runTest(TestSuite.java:243)
	at junit.framework.TestSuite.run(TestSuite.java:238)
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:83)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)

2018-06-13 16:04:14 [ INFO]-main - Log -Log.java(38)  -{
	"catalog_id":1,
	"id":1,
	"name":"测试25"
}
2018-06-13 16:16:35 [ INFO]-main - Log -Log.java(38)  -Config file found ! 
2018-06-13 16:16:35 [ INFO]-main - Log -Log.java(38)  -/last.properties loaded 
2018-06-13 16:16:44 [ERROR]-main - freemarker.runtime -_Log4jLoggerFactory.java(59)  -Error executing FreeMarker template
FreeMarker template error:
The following has evaluated to null or missing:
==> importForeign[c].javaType  [in template "clz.flt" at line 61, column 18]

----
Tip: It's the step after the last dot that caused this error, not those before it.
----
Tip: If the failing expression is known to be legally refer to something that's sometimes null or missing, either specify a default value like myOptionalVar!myDefault, or use <#if myOptionalVar??>when-present<#else>when-missing</#if>. (These only cover the last step of the expression; to cover the whole expression, use parenthesis: (myOptionalVar.foo)!myDefault, (myOptionalVar.foo)??
----

----
FTL stack trace ("~" means nesting-related):
	- Failed at: ${importForeign[c].javaType}  [in template "clz.flt" at line 61, column 16]
----

Java stack trace (for programmers):
----
freemarker.core.InvalidReferenceException: [... Exception message was already printed; see it above ...]
	at freemarker.core.InvalidReferenceException.getInstance(InvalidReferenceException.java:134)
	at freemarker.core.EvalUtil.coerceModelToTextualCommon(EvalUtil.java:465)
	at freemarker.core.EvalUtil.coerceModelToStringOrMarkup(EvalUtil.java:387)
	at freemarker.core.EvalUtil.coerceModelToStringOrMarkup(EvalUtil.java:356)
	at freemarker.core.DollarVariable.calculateInterpolatedStringOrMarkup(DollarVariable.java:96)
	at freemarker.core.DollarVariable.accept(DollarVariable.java:59)
	at freemarker.core.Environment.visit(Environment.java:362)
	at freemarker.core.IteratorBlock$IterationContext.executedNestedContentForCollOrSeqListing(IteratorBlock.java:291)
	at freemarker.core.IteratorBlock$IterationContext.executeNestedContent(IteratorBlock.java:271)
	at freemarker.core.IteratorBlock$IterationContext.accept(IteratorBlock.java:242)
	at freemarker.core.Environment.visitIteratorBlock(Environment.java:595)
	at freemarker.core.IteratorBlock.acceptWithResult(IteratorBlock.java:107)
	at freemarker.core.IteratorBlock.accept(IteratorBlock.java:93)
	at freemarker.core.Environment.visit(Environment.java:326)
	at freemarker.core.Environment.visit(Environment.java:332)
	at freemarker.core.Environment.process(Environment.java:305)
	at freemarker.template.Template.process(Template.java:378)
	at org.docshare.orm.ConfigCreator.main(ConfigCreator.java:123)
2018-06-13 16:17:58 [ INFO]-main - Log -Log.java(38)  -Config file found ! 
2018-06-13 16:17:58 [ INFO]-main - Log -Log.java(38)  -/last.properties loaded 
2018-06-13 16:18:37 [ INFO]-main - Log -Log.java(38)  -Config file found ! 
2018-06-13 16:18:37 [ INFO]-main - Log -Log.java(38)  -/last.properties loaded 
2018-06-13 16:49:55 [ INFO]-main - Log -Log.java(38)  -Config file found ! 
2018-06-13 16:49:55 [ INFO]-main - Log -Log.java(38)  -/last.properties loaded 
